### ISSUE TITLE
Web version of cards

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#115]
Link is shared from the app on social media or via text message (SMS) or copied and pasted. Also the same links when automatic linking to Twitter or Facebook.

Important: this is public view that everyone can see. 
That's why it's important that sensitive information is stripped away. The card can not be opened, neither can the map or anything. It's just an image. As you can see we also change the text to the default public view text: "We are a non-profit ridesharing movement who share equally or offer rides for free. Open this card in our app."

Here's the view from mobile device: 
![web_version](https://user-images.githubusercontent.com/10048880/34781930-70d30f14-f627-11e7-815e-adcd8b0f22cd.jpg)

Here's the view IF viewed on desktop or any other larger screen. Design is the centered:
![web_version_on_desktop](https://user-images.githubusercontent.com/10048880/34782017-b6bae5f6-f627-11e7-90d1-19ab3ed6a535.jpg)

**Comment by MattiasJay** [comment]
Other things to check of about web version of cards:
- [x] META tags for search engines to pick up on; samåkning, skjutsgruppen, skjutsgrupp, samåka, samåk, ridesharing, rideshare, sharing, ride, rides, rörelse, ideellt, ideell, non-profit, non profit, movement, the ridesharing movement, samåkningsrörelse, dela lika, dela
- [x] And automatically add the /from/ and /to/ locations of the ride as tags as well

**Comment by MattiasJay** [comment]
This is still not correct.

1) Are the meta tags really there? I don't find any of our rides or groups when googling any of the tags above. Do you find them when googling, @anjhero @sachit-singh @ruchidhami ?

2) The design is wrong. See desktop design above. When opening on desktop now the ride tops on top of screen, and also not correct design of the card.

**Comment by anjhero** [comment]
@MattiasJay 

1. Yes, the meta tags are there. If you inspect element in the browser and look inside the <head> tag, you can see the tags. Not sure if Google works that way. I don't think it will automatically start appearing when you google the meta tags. A lot of other factors go into Search Engine Optimization. 
<img width="1284" alt="screen shot 2018-07-04 at 1 36 18 pm" src="https://user-images.githubusercontent.com/528549/42264039-4e583850-7f8f-11e8-8e16-83aba19af4e6.png">


2. Do you mean the card sticks at the top of the browser and does not vertically center?

**Comment by anjesh** [comment]
Please reopen if there's still issue.
