### ISSUE TITLE
Friends of Friends

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#127]
- [x] FOAF is tested directly in neo4j cli/API 
- [x] issues are listed here after the test

Here are the different versions of the Friends of Friends-connection I could find.

For small versions beneath comments keep the short arrow format, even for just one degree of seperation (three avatars) as shown in this example. Exeption: IF participants are friends directly, no seperation, then don't show anything. Se more comments on this on inVision: https://invis.io/DZFAF6Z6A#/272958149_Friends_Of_Friends

![friends_of_friends](https://user-images.githubusercontent.com/10048880/34826813-5ef777e2-f6d8-11e7-9a63-5d59ef2521f1.jpg)

**Comment by MattiasJay** [comment]
We need to pump this up as urgent @manishgs @anjesh and @anjhero since I still don't see all my friends when trying to share anything in the app, or adding people to groups.

**Comment by MattiasJay** [comment]
Still something wrong here @anjhero  @anjesh ; Looking at the participant  ”Frida Brännlund” 10662. According to this my friend Emil knows Isak, but he doesn’t.

**Comment by MattiasJay** [comment]
On our meeting, sept 25th:

- The above issue with participant 10662 is ok for now. A bit unclear, but still we will leave it for now (more important things to do)
- The above "extended view" in the design is still not implemented.
- spelling mistake in the app on "You are friends of friends!"

**Comment by shresthaKiran** [comment]
- [x] Implement extended view
- [x] Correct spelling to "You are friends of friends!"

**Comment by ruchidhami** [comment]
This issue has been resolved.
