### ISSUE TITLE
Design fixes, feed.

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#147]
I talked with @samitalalchan on the issue about the menu and started to go through other design fixes at the same time. Here's a separate issue about that. These design fixes:

![menu_etc](https://user-images.githubusercontent.com/10048880/34950570-d10b84ca-fa13-11e7-90d7-6424a3dc3194.jpg)

**Comment by anjhero** [comment]
@saugatmaharjan check this on various phone screens.

**Comment by MattiasJay** [comment]
Good that you're getting back to this @saugatmaharjan @anjhero . We need to fix the feed so it's according to design. The "how it should look" part on the picture above is still valid. One of the things you can see directly are the size of the texts and the spacing. As a good example: look at the card; it has three lines of text and white space between it and the speech bubble. Compare this to our current app that has two lines of text and almost no white space between it and the speech bubble.

**Comment by shresthaKiran** [comment]
This issue has been resolved.
