### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#160]
You find all the correct fonts on the Google Drive.

**Comment by MattiasJay** [comment]
I know you been having problem with the fonts, and all fonts are not added yet. Maybe this is something you can help with @lindanordstrom ? Ping @saugatmaharjan @aayushrijal @manishgs  and issue #342 for reference.

**Comment by anjhero** [comment]
Lets close this if the fonts are added according to the design @saugatmaharjan

**Comment by MattiasJay** [comment]
There's a lot of work to do on this @anjhero @saugatmaharjan .

**Comment by shresthaKiran** [comment]
This issue has been resolved.
