### ISSUE TITLE
Group: Show info during Scrolling

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#162]
Scrolling down in a group turns the top to a box with back arrow, name of group and map.

Like this: https://projects.invisionapp.com/d/main#/console/12489615/273986458/comments

**Comment by anjhero** [comment]
Add the following in the top bar after scrolling down:
- [ ] Name of the group
- [ ] Map

**Comment by shresthaKiran** [comment]
Referenced in #519

**Comment by shresthaKiran** [comment]
Referenced in #519
