### ISSUE TITLE
Sharing ride in Group

### ISSUE THREAD

**Issue by samitalalchan** [Skjutsgruppen/skjutsgruppen-reactnative#166]
@MattiasJay While sharing ride inside a group from the feed list or while creating ride itself, the text that appears as in design from invision as below, Is that text from the ride description or should we add a text field while sharing as in Facebook.
![share](https://user-images.githubusercontent.com/23309084/35081548-f6a4aa10-fc3c-11e7-8fba-53e811fd42bc.png)

**Comment by shresthaKiran** [comment]
This issue has been resolved.
