### ISSUE TITLE
Feed Map: pulsing purple dot

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#180]
The map in the feed centers on closest ride. It should instead center on my position with the pulsing purple dot. 

The map serves as an overview of what's going on in the movement, same as http://skjutsgruppen.nu/search

Center the map on me on my position (the pulsing purple dot) AND show the closest rides. This could mean that the map is centered on me in Sweden but the closest ride is in Kenya, Africa. Then the map is zoomed out so it still has me in the center and shows the closest ride in Kenya.

Zooming in and out loads rides, so potentially I can see everything going on in the movement everywhere in the world right now, just like the standard view of http://skjutsgruppen.nu/search .

**Comment by ruchidhami** [comment]
@MattiasJay  Pulsing is now work for IOS . Can you please confirm it?

**Comment by ruchidhami** [comment]
As per discussion, this has been implemented for IOS only.
