### ISSUE TITLE
miscellaneous query 

### ISSUE THREAD

**Issue by samitalalchan** [Skjutsgruppen/skjutsgruppen-reactnative#205]
@MattiasJay We have few query in our way to development... We want to be clear about few things before we start some new functionality and new design

1. Overall process of admin of group. Does he/she has to be participants of the group? How many admins can be there? Once owner assign other user as admin can he revoke the permission? Can an admin(not owner) add another admin?

2. Overall flow of report (ride/comment/user/experience)

3. According to new design of add rides, while adding rides with return rides... there is no design for adding return rides.  

4. How should we list the active rides? In order of created date or ride dates 

5. Conventions for photo file names - The file names that has been stored with the legacy/old data, does not match with the photographs of users provided. There seems to be certain conventions that has been used which we do not know about.

**Comment by shresthaKiran** [comment]
This issue has been resolved.
