### ISSUE TITLE
IF return ride

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#212]
IF particpant descides to make a return ride (which is default setting when creating a ride, they have to opt out of this) THEN:

1. This screen is shown after the first round: https://projects.invisionapp.com/d/main#/console/12489615/276538423/preview

2. When clicking "Add return ride" THEN the process starts over again, bringing back participant to this: https://projects.invisionapp.com/d/main#/console/12489615/274566421/preview

BUT this has changed:
- [x]  The header changes from "Offer a ride" or "Ask for a ride" to "Add return ride"
- [x]  Photo is prefilled (same photo as previous ride), can be changed
- [x]  Text is prefilled (same as previous ride), can be changed
- [x]  Distance is prefilled but reversed from previous ride, can be changed
- [x]  Remember to reverse the stops in between as well
- [x]  Delete "Are you making a return ride?" section
- [x]  Same selection as was made in the previous ride is pre-checked in the last "Share and publish" step. Can be changed.

3. The last screen showed is this one: https://projects.invisionapp.com/d/main#/console/12489615/275348987/preview

**Comment by anjhero** [comment]
@saugatmaharjan can you check on this?

**Comment by shresthaKiran** [comment]
This issue has been resolved.
