### ISSUE TITLE
Trip: IF offering a ride IN an asked for ride

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#214]
Offering a ride IN an asked for ride also follows basically the same process as ordinary way of adding an offered ride, or adding rides in groups, but with important differences.

1. Participant can start to write a comment in the asked for ride and then press "Suggest a ride", "Offer a ride" or "comment", see this slide: https://projects.invisionapp.com/d/main#/console/12489615/276107163/preview

2. IF she or he choose to offer a ride they are forwarded to due process in the add section with these changes:

- [x] Comment from above comment section is prefilled in the text box. This can be changed.
- [x] "From" and "To" is pre filled from what the asked for ride has asked for. This can be changed.
- [x] Scroll the calendar to the date the asked for ride has asked for and both show and prefill that date. This can also be undone (by simple clicking the ball again, like always).
- [x] The same with time, prefill the time based on what the asked for ride has asked for. Can be changed as well.
- [x] On the last step, share and publish, the participant who asked for the ride is pre-checked and can *not* be unchecked. And the name and avatar tops the list like this: https://projects.invisionapp.com/d/main#/console/12489615/276592360/preview
- [x] Also, on the last step tweet is changed to a tweet to the @TwitterName of that participant IF both participants has Twitter connected. This can be a bit tricky and also need a customized tweet, same as is in the current system. Please look this up in the current system and get back to me. I've made a note about this on inVision here: https://projects.invisionapp.com/d/main#/console/12489615/276592360/comments

3. Two different things will happen if it is a return ride or not return ride:

If return ride
- [x] IF return ride: https://projects.invisionapp.com/d/main#/console/12489615/276594126/preview
- [x] Note here that there is no menu. We are streamlining the process here to bring the participant back to the conversation of the asked for ride.

If no return ride or after adding a return ride and then coming back to the last step again:
- [x] Don't show a last step like in all other versions of this
- [x] Instead, bring the participant back to the ride and scroll down to the "participant x has offered a ride". I have marked where this happens with a note here: https://projects.invisionapp.com/d/main#/console/12489615/276102750/comments
- [x] The comment above the box in the design above is the comment made in step 2 above.

4. Lastly, an important feature in the current system is pretty small but important to link rides and groups logically. It's a small text line at the end of the ride offered ride that is offered in an asked for ride, something like "I offered this ride in participant x's ride" blue and and as a link.

I tried to offer a ride to an asked for ride in the current system now to see _exactly_ what this line says, but that whole function seems to be down on the homepage right now. It's very well phrased and we been working on this before, so I would like to know what the phrase is. Look this up in the code and get back to me.
- [x] Look up the phrase used and get back to Mattias.

**Comment by ruchidhami** [comment]
This issue has been resolved.
