### ISSUE TITLE
Feed List logic 

### ISSUE THREAD

**Issue by samitalalchan** [Skjutsgruppen/skjutsgruppen-reactnative#215]
@MattiasJay 

1. We are confused about how to list the ride card if a ride has recurring rides in the feed page. The logic we are implementing or on the process of implementing is, **Only one card and if it has return ride then two cards** of the ride is shown at the feed screen. 
If a ride has recurring ride as a1 (feb 2), a2 (feb 3) and a3 (feb 4) and it has return ride as b1 (mar 1), b2 (mar 2). There will be only two cards in the feed page. 

    - If today is feb 1 or feb 2 then, cards for a1 ride and b1 ride is shown. 

    - If today is feb 3 then, cards for a2 ride and b1 ride is shown. 

    - If today is feb 20 then card for b1 is only shown and so on.

2. While listing the rides in the feed, we use the logic **the latest updated first ( created, commented)**. 

I read the documentation you have shared but i did not find anything related to this issue so, it will be wonderful if you could help us as soon as possible.

**Comment by MattiasJay** [comment]
We need to come back to this @samitalalchan @anjesh @anjhero ,

the feed logic does not seem to be implemented according to above.

**Comment by anjesh** [comment]
https://github.com/Skjutsgruppen/skjutsgruppen-reactnative/issues/436 and https://github.com/Skjutsgruppen/skjutsgruppen-reactnative/issues/174 are to be addressed in this feed logic issue

**Comment by MattiasJay** [comment]
Note to self; the importance of #436 and #174 

- [x] 436 fixed

- [x] 174 fixed
