### ISSUE TITLE
Admin: Report Admin Process

### ISSUE THREAD

**Issue by samitalalchan** [Skjutsgruppen/skjutsgruppen-reactnative#218]
@MattiasJay 
Hope you have already finalized overall flow of report (ride/comment/user/experience). If yes please share it with us here.

**Comment by anjhero** [comment]
Reopening it to build the admin panel for the report feature. The admin panel does the following:

- [x] List of all the reports
- [x] Include all the information about the ride and/or participant involved
- [x] Both the one who reported and the one who got reported

Later on, the panel will evolve to include following:
- Report admin workflow
- [x] IF done, mark “Done”
- [x] IF working on, mark “Working on” and who of the admins who has marked it “working on”
- [x] Ability to do directly
- [x] Remove participant completely
- [x] Block the participant from ever being able to use the app again (possible?)
--------------
- [x] Separate list of done reports
- [x] Separate list of “working on”.

**Comment by ruchidhami** [comment]
This issue has been resolved.

**Comment by ruchidhami** [comment]
This has been done. Thanks :)
