### ISSUE TITLE
Push notification 

### ISSUE THREAD

**Issue by samitalalchan** [Skjutsgruppen/skjutsgruppen-reactnative#219]
@MattiasJay 
I have created a new tab in the google sheet i have shared with you for push notification. Please update the doc as per required.
https://docs.google.com/spreadsheets/d/1ADTpRYuC8Jy0BU6MV1GIWRE_eVs7pK9ifHtr1AbsMJY/edit#gid=1028558955

**Comment by shresthaKiran** [comment]
This issue has been resolved.
