### ISSUE TITLE
Clarification on "offered", "asked for" and "conversations" on the profiles.

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#222]
I see now in the latest build that we haven't been clear on what "offered", "asked for" and "conversations" means in the profiles.

If we use the participant Johline as an example: https://projects.invisionapp.com/d/main#/console/12489615/272306567/comments#project_console

- Offered is rides that she has offered
- Asked for are rides that she has asked for
- Conversations are _other_ participants rides that Johline has commented on

Also, now the design for these different selections are on inVision and the Drive as well. 

- [x] Note that the Experience symbol (polaroid camera) is next ro rides that have a published Experience that Johline is tagged in.
- [x] This is important so double check this; the symbol should not be shown if there _is_ an Experience but Johline is _not_ tagged.

**Comment by shresthaKiran** [comment]
This issue has been resolved.
