### ISSUE TITLE
Experience: Templated email to all tagged

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#227]
1. IF published THEN e-mail the photo to all tagged
2. E-mail includes link to web version of Experience

**Comment by sachit-singh** [comment]
Email template for:
 - [x]   Verify process during registration
 - [x]   Change e-mail in Profile page
 - [x]   Publish Experience
 - [x]   E-mail this experience
 - [ ]   E-mail HTML code for group (if open group, closed groups can you not get a code for)
 - [ ]  E-mail HTML code for ride
 - [x]   Forgot password

**Comment by anjesh** [comment]
embed related issues are addressed here https://github.com/Skjutsgruppen/skjutsgruppen-reactnative/issues/327
