### ISSUE TITLE
All the different tweets and Facebook messages in Swedish and English

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#230]
When ever an participant is posting to Twitter or Facebook there's a special message. 

Check of this list:

- [x] On Twitter we make /from/ and /to/ destinations into hashtags.
- [x] ...On Facebook we don't make them into hashtags 😀 
- [x] The images connected to the links should be the photo of the ride/group/Experience and if no photo show the map of the ride/group

- [x] Look at issue 231 for our short link skjts.se

# Add

### Twitter:

- [x] In Swedish:

- Jag vill samåka mellan Stockholm och Göteborg den 16/5. http://linktotheWebversion 
#skjutsgruppen #DelaLika 

- [x] In English: 

- I want to share a ride between #Stockholm and #Göteorg on May 16th. http://linktotheWebversion #RidesharingMovement #ridesharing #ShareAlike #skjutsgruppen  

### Facebook: 

- [x] In Swedish:

- Jag vill samåka mellan Stockholm och Göteborg den 16/5. Är det någon som har
ett förslag? http://linktothetrip . #skjutsgruppen 

- [x] In English: 

- I want to share a ride between #Stockholm and #Göteorg on May 16th. Do anyone have a suggestion? http://linktotheWebversion #RidesharingMovement  

### Twitter:

- [x] In Swedish:

- Jag erbjuder #samåkning mellan #Stockholm och #Göteborg den 16/5. http://linktotheWebversion #skjutsgruppen #DelaLika 

- [x] In English:

- I'm offering a ride between #Stockholm and #Göteborg on May 16th. http://linktotheWebversion #RidesharingMovement #ridesharing #ShareAlike #skjutsgruppen  

### Facebook

- [x]  In Swedish:

- Jag erbjuder samåkning mellan Stockholm och Göteborg den 16/5. Vill du följa med? http://linktotheWebversion #skjutsgruppen

- [x]  In English:

- I'm offering a ride between Stockholm and Göteborg on May 16th. Would you like to join? http://linktotheWebversion #RidesharingMovement  

### Twitter

- [x] In Swedish: 

- Jag har precis lagt till gruppen **/name of group/** hos #Skjutsgruppen. Vill ni vara med och samåka med oss? http://linktotheWebversion . #Skjutsgruppen #DelaLika 

- [x] In English:

- I've just added the group **/name of group/** at The #RidesharingMovement . Would you like to rideshare with us? http://linktotheWebversion #ridesharing #ShareAlike #skjutsgruppen  

### Facebook

- [x] In Swedish: 

- Jag har precis lagt till gruppen **/name of group/** hos #Skjutsgruppen. Vill ni vara med och samåka med oss? http://linktotheWebversion

- [x] In English:

- I've just added the group **/name of group/** at The #RidesharingMovement . Would you like to rideshare with us? http://linktotheWebversion

# Commenting on a ride that is offered

### Twitter if both participants has Twitter activated

- When commenting **IF** both participants has Twitter activated **AND** has not opted out (unchecked the checkbox): A tweet is sent from the one commenting to the one offering the ride (from their OWN Twitter
accounts) with a link to the trip and the following message:

- [x] In Swedish:

- Hej @TwitterUSername! Jag vill samåka med dig mellan #Stockholm och #Göteborg 16/5. http://linktotheWebversion . #skjutsgruppen #DelaLika #swgreen 

- [x] In English:

- Hi @TwitterUSername! I want to rideshare with you between #Stockholm and #Göteborg on May 16th. http://linktotheWebversion . #RidesharingMovement #ridesharing #ShareAlike #skjutsgruppen 

### Twitter if only the one commenting has Twitter activated:

- [x] In Swedish:

- Jag har bett att få samåka med **/first name of the one who has offered the ride/** mellan #Stockholm och #Göteborg den 16/5. http://linktotheWebversion . #skjutsgruppen #DelaLika

- [x] In English:

- I've asked **/first name of the one who has offered the ride/** to share a ride between #Stockholm and #Göteborg on May 16th. http://linktotheWebversion . #RidesharingMovement #ridesharing #ShareAlike #skjutsgruppen 

### Facebook

- A Facebook status message is posted to the participant who commented's Facebook timeline:

- [x] In Swedish:

- Jag har bett att få samåka med **/first name of the one who has offered the ride/** mellan Stockholm och Göteborg den 16/5. Se resan här: http://linktotheWebversion

- [x] In English:

- I've asked **/first name of the one who has offered the ride/** to share a ride between Stockholm and Göteborg on May 16th. Se the ride here: http://linktotheWebversion

# Sharing an published Experience

### Twitter if participants tagged in the Experience have Twitter

- IF there are participants tagged in the Experience who have Twitter connected this is a perfect opportunity to connect them all and the one sharing the Experience.

- [x] In English:

- @Twitterusername @TwitterUsername @Twitterusername made a ride with The #RidesharingMovement : http://linktotheWebversion #ShareAlike #ridesharing 

- [x] In Swedish:

- @Twitterusername @TwitterUsername @Twitterusername samåkte med The #Skjutsgruppen : http://linktotheWebversion #samåkning #swgreen #DelaLika  

### Twitter if participants tagged in the Experience **NOT** have Twitter

- [x] In English:

- An Experience with The #RidesharingMovement : http://linktotheWebversion #ShareAlike #ridesharing 

- [x] In Swedish:

- Kolla! Ännu en #samåkning med #Skjutsgruppen : http://linktotheWebversion #samåkning #swgreen #DelaLika

### Facebook

- [x] In English:

- An Experience with The #RidesharingMovement : http://linktotheWebversion #ShareAlike #ridesharing 

- [ ] In Swedish:

- Kolla! Ännu en #samåkning med #Skjutsgruppen : http://linktotheWebversion #samåkning #swgreen #DelaLika

**Comment by MattiasJay** [comment]
**This looks great everyone! Good job!**

---

Feedback:

@sachit-singh : 

 - [x] it should not be a big "S" in "RideSharing". The hashtag should be #RidesharingMovement 

- [x] same with #ridesharing 

- [x] same with #ShareAlike (in the version above there's a big "L")

---

@samitalalchan 
Here are the ones that you asked for:

## When a participant shares others ride

### Twitter

- [x] Important IF: IF the one who made the ride has Twitter connected to us, then change the names below to the Twitter nick.

-  [x] In Swedish if offer: 

- /first name of the one who has offered the ride/ erbjuder samåkning mellan #Stockholm och #Göteborg den 16/5. http://linktotheWebversion . #skjutsgruppen #DelaLika

-  [x] In Swedish if asked for: 

- /first name of the one who has offered the ride/ ber om skjuts mellan #Stockholm och #Göteborg den 16/5. http://linktotheWebversion . #skjutsgruppen #DelaLika

- [x] In English if offer:

-   /first name of the one who has offered the ride/ offers a ride between #Stockholm and #Göteborg on May 16th. http://linktotheWebversion . #RidesharingMovement #ridesharing #ShareAlike #skjutsgruppen

- [x] In English if asked for:

-   /first name of the one who has offered the ride/ asks for a ride between #Stockholm and #Göteborg on May 16th. http://linktotheWebversion . #RidesharingMovement #ridesharing #ShareAlike #skjutsgruppen

### Facebook

-  [x] In Swedish if offer: 

- /first name of the one who has offered the ride/ erbjuder samåkning mellan Stockholm och Göteborg den 16/5. http://linktotheWebversion . #skjutsgruppen

-  [x] In Swedish if asked for: 

- /first name of the one who has offered the ride/ ber om skjuts mellan Stockholm och Göteborg den 16/5. http://linktotheWebversion . #skjutsgruppen

- [x] In English if offer:

-   /first name of the one who has offered the ride/ offers a ride between Stockholm and Göteborg on May 16th. http://linktotheWebversion . #RidesharingMovement 

- [x] In English if asked for:

-   /first name of the one who has offered the ride/ asks for a ride between Stockholm and Göteborg on May 16th. http://linktotheWebversion . #RidesharingMovement 


## When a participant shares others group

### Twitter

- [x] In Swedish: 

- Kolla in gruppen **/name of group/** hos #Skjutsgruppen. http://linktotheWebversion . #Skjutsgruppen #DelaLika 

- [x] In English:

- Check our the group **/name of group/** at The #RidesharingMovement . http://linktotheWebversion #ridesharing #ShareAlike #skjutsgruppen  

### Facebook

- [ ] In Swedish: 

- Kolla in gruppen **/name of group/** hos #Skjutsgruppen. http://linktotheWebversion

- [ ] In English:

- Check out the group **/name of group/** at The #RidesharingMovement . http://linktotheWebversion


## When a participant shares his or her location

### Twitter

- [x] In Swedish: 

- Jag samåker just nu! Se var jag är live på den här kartan: http://linktotheWebversion . #Skjutsgruppen #DelaLika 

- [x] In English:

- I'm ridesharing right now! See where I am live on this map: http://linktotheWebversion #RidesharingMovement #ridesharing #ShareAlike #skjutsgruppen  

### Facebook

- [ ] In Swedish: 

- Jag samåker just nu! Se var jag är live på den här kartan: http://linktotheWebversion . #Skjutsgruppen #DelaLika 

- [ ] In English:

- I'm ridesharing right now! See where I am live on this map: http://linktotheWebversion #RidesharingMovement #ShareAlike 


## When a user shares others experience.

... this one we already have in the list above @samitalalchan , or is there another sharing of Experience you're thinking of that I not cover above?


## _"When a user offers a ride inside a asked for ride from comment section. I do guess this will be similar to Commenting on a ride that is offered as above."_

This one will be the same as when adding an offered ride (same as above) ,
since the link will go to the newly created offered ride (not to the asked for ride) : 

### Twitter:

- [x] In Swedish:

- Jag erbjuder #samåkning mellan #Stockholm och #Göteborg den 16/5. http://linktotheWebversion #skjutsgruppen #DelaLika 

- [x] In English:

- I'm offering a ride between #Stockholm and #Göteborg on May 16th. http://linktotheWebversion #RidesharingMovement #ridesharing #ShareAlike #skjutsgruppen  

### Facebook

- [ ]  In Swedish:

- Jag erbjuder samåkning mellan Stockholm och Göteborg den 16/5. Vill du följa med? http://linktotheWebversion #skjutsgruppen

- [ ]  In English:

- I'm offering a ride between Stockholm and Göteborg on May 16th. Would you like to join? http://linktotheWebversion #RidesharingMovement

**Comment by MattiasJay** [comment]
Ok, go ahead with this @manishgs

**Comment by shresthaKiran** [comment]
As per the policy of facebook (https://developers.facebook.com/docs/apps/review/prefill), we cannot prefill app generated text and should allow users to fill the content. @MattiasJay

**Comment by anjesh** [comment]
We need to check the messaging for location-sharing in twitter only and we can't do anything for facebook as per their policy. Once message for location-sharing in twitter works, we can close this issue as well.
