### ISSUE TITLE
Group: Need to show Standard error box

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#263]
"Group photo is required" should be in the standard error box provided in the designs.

**Comment by RaiSaugat** [comment]
@MattiasJay 
The notification in all the other screens are above the toolbar. But in this screen, putting the error notification below the toolbar seems better. We have provided two screenshots. Can you tell us which one we will be working on?
![screenshot_skjutsgruppen_20180823-133853](https://user-images.githubusercontent.com/19557538/44512512-8e94d500-a6da-11e8-9591-8b44773dcfcd.png)
![screenshot_skjutsgruppen_20180823-133804](https://user-images.githubusercontent.com/19557538/44512510-89d02100-a6da-11e8-8ab6-b866512e1085.png)

**Comment by shresthaKiran** [comment]
@MattiasJay Any update on this?

**Comment by MattiasJay** [comment]
Yes, use the standard error box , grey, and put it bellow the toolbar @shresthaKiran @RaiSaugat

**Comment by shresthaKiran** [comment]
Okay then we will implement screenshot no 2 . @MattiasJay

**Comment by anjesh** [comment]
referenced here https://github.com/Skjutsgruppen/skjutsgruppen-reactnative/issues/519
