### ISSUE TITLE
When opening "share" from anywhere (like sharing from the feed or sharing a group or a ride or whatever) the top and bottom should be fixed, see the design in the provided link.

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#266]
The design and functionality here on inVison: https://projects.invisionapp.com/d/#/console/12489615/273965471/preview

Also, top bar has a shadow and bottom bar has a shadow.

**Comment by shresthaKiran** [comment]
This issue has been resolved.
