### ISSUE TITLE
Group Feed: Showing rides in map

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#278]
When rides are added in a group THEN they will show on the group map (shown just like rides are shown on main map in feed)

This is one of these small features that is very popular in the current homepage; the group map show both the stretch or centers on place (just like you have done it already) AND places out current rides added in or to that group. Here's an example of a group right now: http://skjutsgruppen.nu/g/310

**Comment by MattiasJay** [comment]
...rides added in/to a group are still not shown on group map @anjhero @anjesh .

**Comment by MattiasJay** [comment]
This is not working in current Test Flight version; currently no added rides in the largest group,  "Sthlm - GBG", are seen on the map at all. @shresthaKiran

**Comment by shresthaKiran** [comment]
Referenced in #519
