### ISSUE TITLE
Trip comment

### ISSUE THREAD

**Issue by samitalalchan** [Skjutsgruppen/skjutsgruppen-reactnative#281]
When we first started the trip detail page we had trip comment only. But now as told by you, the comment section will contain comment itself, Suggested ride and offered ride in case of Asked for ride, Share your location n hrs before the ride begins, Make an experience n hrs after the ride has begun, Published experience. **So comment is no more treated as comment but as feed similar to that of Group.** 

A. Right now the comment in group and trips are listed in opposite way. In groups it is listed in latest at top order whereas in case of trip it is listed in the order of latest at the bottom( same like Facebook). I guess it will be less confusing for user if both are listed in same order. Isn't it??

B. Are we going to suppose that the offered ride inside asked for ride, make an experience, suggested ride as comment as well????? What should the comment number of the trip in the trip feed be.
![comment](https://user-images.githubusercontent.com/23309084/36526579-e0e6144c-17d6-11e8-9e65-986d50d5c358.png)
 

You have said that a user can delete comments as well as the suggested rides, offered rides and published experience feed inside comment section. So i do have few queries.
1. I guess **Delete comment** text should be change to more universal text as offered ride, suggest ride and experience cannot be termed as comment. That's my opinion.

Lets suppose we are inside the trip detail of asked for a ride named ABC

2. If a user offers a ride name XYZ inside the trip ABC from the comment section (suggest/offer/comment), the feed will be created inside the trip as well in the main feed ( we talked abt this in another issue).
 Can owner delete this feed XYZ trip inside the trip ABC. If he does so, what will happen.
    2a. Only feed inside the trip will be deleted, but trip will not be deleted.
    2b. The trip itself will be deleted.
![offer](https://user-images.githubusercontent.com/23309084/36526061-c6c4a67a-17d4-11e8-9be4-af64e946805d.png)

3. Lets suppose a user creates the experience for the trip ABC. What will happen when the user deletes the experience feed from the comment section. 
    3a. Only experience feed inside the trip  will be deleted.
    3b. Experience will be deleted. 

![download 1](https://user-images.githubusercontent.com/23309084/36526071-d127ee7e-17d4-11e8-89fb-92254e4bd1b6.png)

It ended up being quite long. Ping me if you don't get what i am talking abt:). @MattiasJay

**Comment by MattiasJay** [comment]
1. Samita suggest @samitalalchan s ride

2. Yes! It's like a normal ride... _but_ ... have you seen the designs? 😉 
- There are som slight differences. 

- Look under "Asked for ride" in inVision and you see the designs that are different. 

- [x] Grey checkbox of particpant who is offered ride, on top of everything: 
 https://projects.invisionapp.com/d/#/console/12489615/276592360/preview

- [x] Special last page with no menu, but with two distinct options: https://projects.invisionapp.com/d/#/console/12489615/276594126/preview

**Comment by shresthaKiran** [comment]
This issue has been resolved.
