### ISSUE TITLE
Mute

### ISSUE THREAD

**Issue by samitalalchan** [Skjutsgruppen/skjutsgruppen-reactnative#282]
@MattiasJay 
We can perform mute action on ride and group. When we mute ride/group 
1. There will be no push notification related to the muted ride/group. Am i correct??
2. Will the message related to the muted ride/group will be shown in the new section of "Messages & Group" screen or not.

**Comment by anjesh** [comment]
https://github.com/Skjutsgruppen/skjutsgruppen-reactnative/issues/504 will be updated once mute is working.
