### ISSUE TITLE
Now added: accepting or rejecting participants who wants to participate in closed groups.

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#291]
- Entry point: From "Group information" IF enabler: https://projects.invisionapp.com/d/#/console/12489615/276831278/preview

- Goes here:
https://projects.invisionapp.com/d/#/console/12489615/282109875/preview

- Entry point if you get a message about someone wanting to participate in "your" group, in "Messages and groups". Go straight here:
https://projects.invisionapp.com/d/#/console/12489615/282109875/preview

**Comment by anjesh** [comment]
Please create another ticket if there's issue in this group feature.
