### ISSUE TITLE
Sticky bar during scrolling

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#317]
- [x] "top white box" scrolls away when scrolling in an upwards motion in trip detail page
- [x] "top white box" scrolls away when scrolling in an upwards motion in groups detail page
- [x] "top white box" appears when scrolling in the other direction in trip detail page
- [x] "top white box" appears when scrolling in the other direction in groups detail page

--

Make the "top white box" in rides and groups scroll away when scrolling in an upwards motion, and appear when scrolling in the other direction --- as in the provided example

--

Latest build is great, and also shows two cases where we need to save space for the feed:
- rides
and
- groups

Let's scroll away the "top white box" when scrolling in an upwards motion, and appear when scrolling in the other direction --- as in the example from the Omni app e-mailed to @samitalalchan @anjesh and @anjhero

**Comment by ruchidhami** [comment]
This issue has been resolved.
