### ISSUE TITLE
sharing location: showing icon

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#318]
- [x] when sharing location, participants see the glowing icon in the menu

On this weeks weekly meeting we talked about the need of showing the participant where she or he is currently sharing location.

We need to have a "don't be evil" approach and show this as clearly as possible so they can easily access and stop the sharing if needed.

It seems to me like the best place for this is "Messages & groups".

My suggestion is to

**1. IF sharing location - Show the pulsing circle (used in right corner of start feed and on our maps everywhere to show your location)** in the menu

- pulsing in the menu like this:
![puls_in_menu](https://user-images.githubusercontent.com/10048880/37241436-4665bfdc-2459-11e8-9c77-3ef5bce9357a.jpg)

- The pulsing is the same kind of pulsing as you see in the Telegram app that we use for reference.
- It should pulse within the white menu box, not outside it (even if I made this fast mockup now where the circle is slighly outside the box, this should not be the case)

**2. IF sharing location this section will appear in Messages and groups:**

- https://projects.invisionapp.com/d/#/console/12489615/284193966/preview

Give me your feedback on this @samitalalchan @anjesh @anjhero

**Comment by MattiasJay** [comment]
Since we now have released the app we need to bring up and prioritize this issue @anjesh , @anjhero , @manishgs , @aayushrijal , @shresthaKiran , @sachit-singh , @roxcity  @saugatmaharjan  and @umuieme  . The participants need to be able to control their sharing of location for the same reasons as we've been talking about participant agreement and privacy policy.

A couple of weeks ago I saw that you had actually implemented this in the Android app, but it doesn't seem to be there anymore now. Give me an update about this.

**Comment by ruchidhami** [comment]
This issue has been resolved.
