### ISSUE TITLE
Design for "only searching for groups" and when all options are selected in search.

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#323]
I saw that we were missing two designs in search:

1. Selecting all options in search, and hence showing groups as well:
https://projects.invisionapp.com/d/#/console/12489615/284347516/preview

2. _Only_ searching for groups, in search:
https://projects.invisionapp.com/d/#/console/12489615/284348064/preview

All the different screens for search are found under the section "Search" in inVision. There are a couple of different "IF - THEN" scenarios there.

All the designs are on the Drive, in the "Search" folder.

**Comment by shresthaKiran** [comment]
This issue has been resolved.
