### ISSUE TITLE
Embed feature - issues

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#327]
- [x] embed code for trip is emailed to embed-action-initiator
- [x] embed code for open group is emailed to embed-action-initiator
- [x]  enablers of open group is notified about group embed
- [x] embed code for close group is not possible
- [x] embed code for open group should be disabled if later group is changed to closed
- [x] email template for embed code for trip is received and setup
- [x] email template for embed code for group is received and setup

notes
-----

Closed groups can not be embedded due to privacy issues.

IF closed group, then this design: https://projects.invisionapp.com/d/#/console/12489615/285272329/comments

Also, important to remember is that a group can change from Open to Closed, then the embedment need to stop working for those who have already embedded. @samitalalchan

**Comment by MattiasJay** [comment]
Notification e-mail to enabler of group:

"Participant x has ________(something)_____ the HTML code for embedding this group. You get this message because you are the enabler of the group

- You can talk to this participant by commenting in your group: https://skjts.se/xxxx "

**Comment by MattiasJay** [comment]
- [x] Provide template to Ruchi for e-mail to enabler of group

- [x] Provide template to Ruchi for e-mail to one asking for html of group

- [x] template for one asking for trip html (show in the e-mail how it looks)

- [x] template to owner of ride if someone asks for html for it (show in the e-mail how it looks)

**Comment by MattiasJay** [comment]
IF no search results THEN show "bicycle design" https://projects.invisionapp.com/d/main#/console/12489615/274450568/preview

AND the "Add ride" button. The button refers to www.skjutsgruppen.nu

**Comment by MattiasJay** [comment]
@ruchidhami : the first e-mail design, that goes to the enabler(s) of the group, is now on the Drive. Ping @anjhero .

**Comment by ruchidhami** [comment]
@MattiasJay  email design for the enabler of the group has been implemented, Can you please provide other remaining design soon ?

**Comment by MattiasJay** [comment]
@ruchidhami Now all the remaining designs are on the Drive. These scenarios changes the design a little bit:

- [x] IF I ask for the code of my own group, change info to "your group" and remove info about enablers. AND not send notification e-mail to myself :-) 

- [x] IF I ask for the code of my own ride, same as above: change the language to fit AND not send notification e-mail to myself :-) 

One more thing

- [x] The embeded card is clickable and opens app IF on mobile phone, IF on desktop redirect to www.skjutsgruppen.nu

**Comment by MattiasJay** [comment]
Hi again @ruchidhami , now we're close do done. Have you checked the check boxes above as well?

Here are some last things:

- [x] The e-mail I got when you asked to embed my group "Peace & Love World Forum" had this code on top "CTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">" 
- it should not be there and be removed.

- [x] The subject line should be "A participant in your group "Peace & Love World Forum" has gotten the embed code of your group"

- [x] The blue name of the group in the first sentence should be clickable and lead to the group (in this case https://skjutsgruppen.nu/g/201)

- [x] You still have to fix the correct header date as we discussed on Slack. The example in this group; the header is 2018-07-07 but the ride is for July 4th

**Comment by MattiasJay** [comment]
Good work @ruchidhami !

The "North, South, East, West, Anyhwere" options has not translated to the embed feature. See an example here:

This ride https://skjutsgruppen.nu/t/37328 goes from anywhere to Sten Sturegatan 10 but on https://skjutsgruppen.nu/groups/23 it only says "Ludwig Asks for a ride - Sten Sturegatan 10"

- [ ] Fixed

**Comment by ruchidhami** [comment]
@MattiasJay  All of the above list has been implemented. Please re-open if there is missing something.

**Comment by MattiasJay** [comment]
Hi again @ruchidhami , the "North, South, East, West, Anyhwere" is still not fixed. Look at the same links as above; it still only says "Ludwig Asks for a ride - Sten Sturegatan 10"

**Comment by ruchidhami** [comment]
This is now solved.
