### ISSUE TITLE
UI: Wrong size and text of stand-alone recurring ride button

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#328]
In inVision you have three different scenarios right above each other:

- only recurring (long button)
- only return (long button)
- both return and recurring (two smaller versions of the two above next to each other)

Right now only the smaller version is used, which is wrong when it stands alone.

**Comment by shresthaKiran** [comment]
This issue has been resolved. Please re-open if any issue exists.
