### ISSUE TITLE
Feed design

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#380]
Great to be able to test the design on iPhone! And great to have you on board @k2glyph ! Welcome!

 iPhone is crucial for our movement and we have many more iPhone users than Android. Testing on iPhone makes it easier to point out what we have been talking about since January but not always been sure of. Below I've made a screenshot of the build on iPhone 6 and the inVision for the same screen on iPhone 6. What you see are ten different ways we can adjust the build to come in line with the design. It's going to be great!

On Saturday we will have an event here in Sweden where we let the public come and test the app during an Science Festival. Will it be possible to have the feed according to design by then @anjhero @anjesh @samitalalchan  and @k2glyph ?

![feed_feedback_20180418](https://user-images.githubusercontent.com/10048880/38930331-d23136ca-430f-11e8-9b79-15e92b2cd15c.jpg)

**Comment by shresthaKiran** [comment]
This issue has been resolved.
