### ISSUE TITLE
Transifex

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#385]
E-mail from @anjesh on March 23rd:
----

> We can provide that link whenever you are ready. https://github.com/Skjutsgruppen/skjutsgruppen-reactnative is currently private, we can make it public and provide the link to Transifix. I don't have any issue in making it public, though we understand that it's not complete yet. Also it doesn't have to be complete to make it opensource. We need to add Open Source License in the repo. I am up for MIT license https://opensource.org/licenses/MIT, unless you have something else in mind. 
> 
> Do you have any issue in making the repo public?

**Comment by MattiasJay** [comment]
Transifex is now up and running and @manishgs @anjhero and @anjesh is added as administrators. What you need to do now is to upload resources to see how it works.

**Comment by MattiasJay** [comment]
Can we move Transifex to **_done_** now? @manishgs @anjesh @anjhero .

**Comment by anjesh** [comment]
Yes transifix setup is done.
