### ISSUE TITLE
UI: Look and working of menus

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#386]
Menus should open sliding up and close sliding down and have a darkened background, like this example from the iOS Slack app:

![photo_2018-04-20_15-02-13](https://user-images.githubusercontent.com/10048880/39052320-e1a8d64c-44ab-11e8-98fa-5ba15f9424d9.jpg)

**Comment by MattiasJay** [comment]
I see in Test Flight that this is fixed on some menus but not on all, @anjhero and @saugatmaharjan .

**Comment by ruchidhami** [comment]
This issue has been resolved.
