### ISSUE TITLE
Add the following Library a) Google Maps Android API b) Google Places API Web Service c) Static Maps API d) Google Maps Directions API e) Google Maps Geocoding API

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#401]
@samitalalchan asked me to do this:

> 1) Click on the link https://console.developers.google.com/ 2) Add a prjoect and inside the project search and add the following Library a) Google Maps Android API b) Google Places API Web Service c) Static Maps API d) Google Maps Directions API e) Google Maps Geocoding API 3) Generate the API key 4) Provide us the key

**Comment by anjesh** [comment]
I believe this should have been done.
