### ISSUE TITLE
Issues with "messages and group"-search page

### ISSUE THREAD

**Issue by lindanordstrom** [Skjutsgruppen/skjutsgruppen-reactnative#405]
A couple of issues;
Sorry if this is already known

* Cannot navigate back or close the page, there's no way out other than force quit the app

* Cannot search for anything (?) even though I have a couple of messages and a group on that page. Most of the search strings I enter will result in "no results" except for when I am searching for "Mattias" then the app will crash instead 😅

**Tested on**
iPhone 8
iOS 11.3.1
App version 1.0.1 (5)

**Screenshot for no close/back button:**
![img_0432](https://user-images.githubusercontent.com/13778933/39267004-dbf423b8-48cb-11e8-9624-9eaaba031216.PNG)

**Comment by shresthaKiran** [comment]
This issue has been resolved.
