### ISSUE TITLE
Experience and sharing location issue

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#424]
Hi guys! In todays live test it became aparent that the very important sharing location- and Experience functionality does not work at all in both ride feed and "messages & groups". 

We have talked about this in detail in issues regarding sharing location and Experience, so you can look there for how it's supposed to work @samitalalchan @anjhero @anjesh , but I'm adding this issue now to bring this to all of our attention.

In short: both sharing location and Experience are supposed to be in the feed and as push notifications / "messages & groups" like this:

1) Feed: https://projects.invisionapp.com/d/main#/console/12489615/262119235/preview

2) In messages and groups: https://projects.invisionapp.com/d/main#/console/12489615/263059414/preview

----

Now it looks like this and is both very wrong and confusing:
![photo_2018-05-13_17-14-03](https://user-images.githubusercontent.com/10048880/39968724-00e9ed4c-56d2-11e8-8418-0bd25b2e5f64.jpg)

**Comment by MattiasJay** [comment]
Hi again! I like that both Experience and share location is now in the feed, but it's still wrong @anjhero @anjesh @manishgs .

I'll do a check list again and you can check of things:

- [x] Location should appear before ride starts, this is **correct** . But Experience should appear later. Please look at issue #138 for the amount of time that should pass before this appears.

- [x] Generally, read through issue #138 to freshen up memory.

- [x] Both of these are _feed entrys_, just like comments, they should come in order of appearence. If there's comment before them, then location comes after that comment(s). Same for Experience.

- [x] Since they are feed entrys I should recieve a notification in "Messages and groups". See design (link to design above)

- [x] I should also get push notifications for this.

- [x] I have never been able to access or make an Experience from iOS. It just keeps loading. This needs to be tested on your iPhones. Please make an Experience from an actual iPhone before checking this one off.

Lastly,

- [x] This should never have been there. This "Make an Experience" position is totally wrong: 

![wrong](https://user-images.githubusercontent.com/10048880/40236783-ee137112-5aae-11e8-9305-760c346886c2.jpg)

**Comment by MattiasJay** [comment]
Give me an update about this urgent issue @manishgs @anjesh @anjhero .

**Comment by MattiasJay** [comment]
Today I was part of this ride and did **_not_** get a notification to "Make an Experience" - not in the ride feed, not as a push notification and not in "Messages & groups": https://web.skjutsgruppen.nu/t/36296

Hence we need to reopen this issue and it's still urgent @anjhero @anjesh .

Details about the ride: I commented after the ride had started, but this should not influence if I get "Make an Experience" notification or not, since the ride was still within the active time frame and I could have joined the ride along the way within this time frame.

**Comment by anjesh** [comment]
@shresthaKiran can you test from your end and close this issue it's working (also post screenshots).

**Comment by ruchidhami** [comment]
reference on #536
