### ISSUE TITLE
After publishing a bunch of offered rides I don't get the important option to add return ride (even though I've filled in I should have return ride). Also, the design is wrong. Iphone, iOS.

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#429]
Here's how it looks right now in iOS:
![photo_2018-05-14_22-51-27](https://user-images.githubusercontent.com/10048880/40022902-a37d108c-57c9-11e8-80bb-6df2fdd51212.jpg)

___________________________________

And here's how it should look like:
1) The headline of this one: https://projects.invisionapp.com/d/main#/console/12489615/276535594/preview

2) ... combined with the button of return ride on this one: https://projects.invisionapp.com/d/main#/console/12489615/276538423/preview

**Comment by shresthaKiran** [comment]
This issue has been resolved.
