### ISSUE TITLE
Feed: Missing return rides

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#436]
To my understanding we should show return rides link on all rides created at the same time IF they are connected. I just tried this (look for the rides labeled "Spanish party") and I only get the "return ride" link on the first ride but not the rest. Look into this @manishgs @anjesh @anjhero 

![photo_2018-05-18_11-19-18](https://user-images.githubusercontent.com/10048880/40226925-5cd9a124-5a8d-11e8-9083-0556cef8978a.jpg)

**Comment by MattiasJay** [comment]
...also assigning @p-jo for the LOLz of Spanish Party 😆

**Comment by anjesh** [comment]
Will be addressed in https://github.com/Skjutsgruppen/skjutsgruppen-reactnative/issues/215
