### ISSUE TITLE
Info about existing domains.

### ISSUE THREAD

**Issue by sachit-singh** [Skjutsgruppen/skjutsgruppen-reactnative#443]
It seems an upgrade is required to add and redirect a sub domain, as needed, i.e., api.skjutsgruppen.nu that points to the new server. 

Also is the old system to be hosted at something like old.skjutsgruppen.nu and the existing skjutsgruppen.nu to redirected to the web version of the new app? In order to do it seems the current plan on loopia.se needs to be upgraded.

How do we go about this??

**Comment by MattiasJay** [comment]
Do we need to upgrade just to do this? Can you tell me more in detail about this @sachit-singh ; bullet point what we have to do:

- We have this....
- We need this...

@anjhero @anjesh

**Comment by sachit-singh** [comment]
First of all, let me give you an update @MattiasJay .

We just updated ridesharingmovement.org to point to the new server and it worked. So for now the API will be hosted as api.ridesharingmovement.org and ridesharingmovement.org will point to the new Web Version. And skjutsgruppen.nu will point to the old web application (unchanged).

When skjutsgruppen.nu is pointing towards a specific IP, all sub domains will follow the same. In order to host the old web app in old server (lets say Server 1) and the new API and web version in the new version (say Server 2), we would need to point sub domains to a different server.

For example,

 * skjutsgruppen.nu -> Server 1 (old) and api.skjutsgruppen.nu -> Server 2 (new | api) and maybe web.skjutsgruppen.nu -> Server 2 (new | web version). 
 * OR old.skjutsgruppen.nu -> Server 1 (old) and api.skjutsgruppen.nu -> Server 2 (new | api) and skjutsgruppen.nu -> Server 2 (new | web version)

In order to do this, it seems we need to upgrade the plan on Loopia.

But if we only need the API and the new web version, then we would point skjutsgruppen.nu to the new server and then all sub domains will also point accordingly. If this is the case then we would not need to upgrade the plan. But we would need to move the old system to the new server under a sub domain.

What this means is when a domain is pointed to an IP, all sub domains point to the same IP, and to make them point to different locations, the plan needs to upgraded it seems.

I hope I made it clear. Please let me know if you have any confusions.

Regards,

**Comment by sachit-singh** [comment]
@MattiasJay I'm sorry for the confusion. We got a little confused with the interface on Loopia.se. Apologies for the complexity.

The API will now be hosted at api.skjutsgruppen.nu and the web version at web.skjutsgruppen.nu, for now. Later what we can do is move skjutsgruppen.nu to the new web version and host the old system as old.skjutsgruppen.nu or something.

Regards.
