### ISSUE TITLE
iOS - Cannot load next view after accepting privacy policy

### ISSUE THREAD

**Issue by lindanordstrom** [Skjutsgruppen/skjutsgruppen-reactnative#460]
Just keeps loading, nothing happens. After logging in with email and password. 
IOS 11.3.1
iPhone 8

![image uploaded from ios](https://user-images.githubusercontent.com/13778933/40902958-0b087842-67d6-11e8-9520-3de3b1c507a1.png)

**Comment by shresthaKiran** [comment]
This issue has been resolved.
