### ISSUE TITLE
Too many open issues

### ISSUE THREAD

**Issue by nordp** [Skjutsgruppen/skjutsgruppen-reactnative#473]
Hi Skjutsgruppen, nice to meet you!

I checked in here looking for some issues I could solve but I think one big issue is the issues themselves. There are 161 of them, many opened by the same person but it seems like there is no follow-up when they resolve. If this is an open-source project then the issues should be the transparent way of communicating what is going on and what isn't. It's also hard to navigate them since a lot of them talk about the drive or the slack which to my knowledge are private and not reachable for collaborators.

If I'm missing some info about the workflow of skjutsgruppen please fill-in, I'd very much like to contribute to this project but I think issues need cleaning up in order for new participants to easier find and solve them.

**Comment by nordp** [comment]
I also lack documentation on how to:
> Update .env config according to your need.

Since many of these keys are required in order to debug the app, a simple tip on how to get started would improve the "developer onboarding"

**Comment by anjesh** [comment]
Trying out best to close as many issues as possible, and also sorting the issues.
