### ISSUE TITLE
Create a Sendgrid account: https://sendgrid.com

### ISSUE THREAD

**Issue by anjhero** [Skjutsgruppen/skjutsgruppen-reactnative#480]
Create a sendgrid account for sending out various emails to our participants. 

Create an account here: https://sendgrid.com

**Comment by shresthaKiran** [comment]
@MattiasJay  Any update on this issue?

**Comment by MattiasJay** [comment]
Sendgrid account is now created. Since the free version only allows one team member, @anjhero is invited as team member. See your e-mail @anjhero . Ping @shresthaKiran
