### ISSUE TITLE
We need to finally fix that scrolling down scrolls down map in start feed, rides and groups. People are not finding the maps.

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#484]
Reference to this issue: issue #301

**Comment by anjesh** [comment]
Duplicate https://github.com/Skjutsgruppen/skjutsgruppen-reactnative/issues/301

**Comment by MattiasJay** [comment]
Issue #301 only regards start feed, but this is an issue for _all_ maps, rides and groups as well, just to be clear @anjesh .
