### ISSUE TITLE
Wrong text in the web version of groups

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#485]
It should be the actual text of the group, and faded into white, like the design: https://projects.invisionapp.com/d/main#/console/12489615/297297971/preview

**Comment by shresthaKiran** [comment]
Referenced in #519

**Comment by MattiasJay** [comment]
It's still not the actual text of the groups. Example group: https://skjutsgruppen.nu/g/23

To be clear, the rides should have the default text "We are a non-profit...." 
...and groups should have the actual text.

**Comment by shresthaKiran** [comment]
This issue has been resolved.
