### ISSUE TITLE
Moving "Sync contacts" to onboarding

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#490]
1) A newd step 6 in the onboarding. After phone number is confirmed the participant sees this:

![step6_trust_and_security](https://user-images.githubusercontent.com/10048880/42137895-92c5b660-7d74-11e8-8b61-b6c484fd06c6.jpg)

---------------------------

2) Then this:
![step7_trust_and_security](https://user-images.githubusercontent.com/10048880/42137896-9d42fa30-7d74-11e8-8fc9-ce6b01cd4d09.jpg)

---------------------------

3) Then this, and this one is important, because it's the same page when dialogue box opens on it

![step8_trust_and_security](https://user-images.githubusercontent.com/10048880/42137900-b5b6d230-7d74-11e8-8092-ab0cf3b226e9.jpg)

---------------------------

4) Like this; the dialogue box opens
![step8_trust_and_security_dialoguebox](https://user-images.githubusercontent.com/10048880/42137911-d6937512-7d74-11e8-9a5a-d20eeaf06cbc.jpg)

---------------------------

5) And then, what ever happens (OK or not), the participant is welcomed, like this:
![step9_trust_and_security](https://user-images.githubusercontent.com/10048880/42137914-f69b18b0-7d74-11e8-9523-7dddfb66117b.jpg)

All of the files are on the Drive.

**Comment by shresthaKiran** [comment]
This issue has been resolved.

**Comment by MattiasJay** [comment]
I just tried this one out and step four and five are not implemented. Moving this back to issues. @shresthaKiran @anjhero @anjesh

**Comment by ruchidhami** [comment]
@MattiasJay  This issue has been resolved.
