### ISSUE TITLE
My avatar is not seen on web version of cards.

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#496]

**Comment by shresthaKiran** [comment]
This issue has been fixed. Could you please verify it.

**Comment by MattiasJay** [comment]
Nope, look for instance on this ride @shresthaKiran : http://skjts.se/t/38780 . No avatar.

**Comment by shresthaKiran** [comment]
@MattiasJay Avatar of the user of (http://skjts.se/t/38780) ride is visible in our side. Is it not visible in your end?

**Comment by MattiasJay** [comment]
This is weird, because now the avatar is seen on ride http://skjts.se/t/38780 , but not on the ride https://skjutsgruppen.nu/t/38840 in desktop version of chrome. It seems inconsistent @shresthaKiran . Does it have something to do with newly added rides?

**Comment by shresthaKiran** [comment]
No, its not with the newly added rides. Actually, we had used capistrano to deploy branches due to which the path to the image was different. We have fixed this. It should work for all cases now. 
@MattiasJay

**Comment by shresthaKiran** [comment]
This issue has been resolved. Please reopen if there is any issue.

**Comment by MattiasJay** [comment]
Great @shresthaKiran , good job! Move this to "Done" on the Kanban board as well 👍
