### ISSUE TITLE
Link text: very wrong security breach. The real text from the ride is seen in the link description.

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#497]

**Comment by shresthaKiran** [comment]
@MattiasJay We have removed the trip description and added "We are non-profit ridesharing movement who share equally or offer rides for free. Open this card in our app" text instead in the preview link. 

Is it okay to add this text or do you want to update it?

**Comment by shresthaKiran** [comment]
@MattiasJay Any update on this?

**Comment by MattiasJay** [comment]
This is very good @shresthaKiran ! Good job!

**Comment by MattiasJay** [comment]
I discovered that if posting link in any chat program you can still see the real text from the ride, not the generic one. So we still need to fix this @shresthaKiran @anjhero 

Also, there's a spelling error. It is an "a" missing. It is the "a" in bold here:
"We are **a** non-profit ridesharing movement who share equally or offer rides for free. Open this card in our app"

**Comment by ruchidhami** [comment]
This issue has been resolved . @MattiasJay
