### ISSUE TITLE
UI: Calendar should start Monday and need right design

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#499]
Calendar in recurring ride and groups starts with Sunday. And it has the wrong design. It should start with Monday, and have the right design.

**Comment by shresthaKiran** [comment]
This issue has been resolved. Please re-open if issue still exists.

**Comment by MattiasJay** [comment]
Still some design to work on @anjhero @shresthaKiran . When there are both an offered ride and an asked for ride on the same date the calendar should visualize this according to the design. It should be a split ball, half blue half pink. Right now it just shows one color so it's impossible to know that date contains both an offered and an asked for ride.

**Comment by ruchidhami** [comment]
This issue has been resolved.
