### ISSUE TITLE
We really need to activate the e-mail notification from the old homepage.

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#506]

**Comment by shresthaKiran** [comment]
@MattiasJay  could we have more details on this issue please.

**Comment by MattiasJay** [comment]
An aparent big problem is that our participants don't reach each other since they have notifications turned of. An feature in the homepage is that we also send an e-mail when a comment is made. Have you talked about this @shresthaKiran and @anjhero ?

When implementing this will also implement the ability to turn of e-mail notifications in the settings section (in the self-sustaining garden section).

**Comment by shresthaKiran** [comment]
1) Currently, we had used the notifications settings in the settings section whether to send push notification to the user from our server or not. But, if the user has set notification settings **ON**, but hasn't allowed push notification permission in the mobile phone, then the user will not receive the push notification. Should we keep this feature and and add another button to set e-mail notification settings or replace this feature with e-mail notification settings.

2) If the user has turned **ON** e-mail notification in the settings section, does he get e-mail notification only when a comment is made or will he also get e-mail notification of other actions?

3) Also, we might need an email template for this too. Should we just send the commented text or add extra descriptions with the link to the ride or group?

@MattiasJay

**Comment by shresthaKiran** [comment]
@MattiasJay  Any update on this?

**Comment by MattiasJay** [comment]
1) Seems like we can keep the push notification setting and add e-mail setting. Maybe there's something I'm missing here. Do you think we should remove push notification setting @shresthaKiran  @anjesh  @anjhero ?

2) These are the actions where participants should recieve an e-mail:

- [x] When a comment is made in a ride: bundle them IF more than two different participants commenting (se PSD files for examples of one comment and many comments, two different PSDs)
- [x] When comments and rides are added to a group (not when someone joins)
- [x] IF enabler of a closed group and someone asks to join
- [x] When someone has shared something with you (anything basically)
- [x] Someone wants to become friend

3) All of the e-mail templates are now on the Drive (in the folder "E-Mail").

Here are their subject fields:

When a comment is made in a ride:

- [x] Subject line if one comment: Johline has commented on your ride!
- [x] Subject line if more than two different participants has commented: Johline, Lovise and more has commented on your ride!

When comments and rides are added to a group:

- [x] subject: New comments in the group Daily commute to town!

IF someone asks to join a closed group:

- [x] Subject: Johline asks to participate in Daily commute to town

When someone shares something:

- [x] Subject: Johline has shared xxxx with you

When someone wants to become a friend:

- [x] Subject: Johline wants to become friends with you!

**Comment by shresthaKiran** [comment]
1) Before bundling comments in an email, we must have some fixed interval so that the comments made in that interval in a trip will only be bundled. How much should we keep the interval?

2) In your PSD files, there are dynamic links to the app. So, if a user opens the email from mobile, then he/she will be redirected to that group/trip/requests. But, what if the user opens the email from web. Do we remove the button or add something else?

@MattiasJay 
/cc @anjhero

**Comment by MattiasJay** [comment]
1) You mean like a time interval? Let's set it for an hour.

2) All the links in the e-mails shall go to the web version of cards. If no web version and opening on web, then link to www.skjutsgruppen.nu

@shresthaKiran @anjhero

**Comment by shresthaKiran** [comment]
Okay, then we will schedule to send email of bundled comments after an hour. Also, could you please create an account in sendgrid. (#480)

@MattiasJay

**Comment by MattiasJay** [comment]
Updates: 

1) we need to make sure to make a small difference between "comment made on YOUR ride" and "comment made on THE ride xxxx" if not owner of ride.

2) Make sure that the mute functionality works before going live with these e-mails since we're referring to the possibility of muting, @shresthaKiran . Currently mute does not work, see issue #504 

3) Note: IF mutes then no e-mail and no notifications until a) time has passed (see the muting options) or b) mute is turned off.

4) Sendgrid account is now created. Since the free version only allows one team member, @anjhero is invited as team member. See your e-mail @anjhero . Ping @shresthaKiran

**Comment by anjhero** [comment]
@MattiasJay We will require SendGrid's upgraded plan. The 40,000 Emails Per Month plan should do for now.

**Comment by MattiasJay** [comment]
Sendgrid have a problem with our credit card for unknown reason. I have set up an issue conversation with them now, so hopefully we'll hear from them soon. Until then, I see that the plan we're on is a trial plan for 40 000 e-mails per month, so we can still go ahead @anjhero .

This upcoming weekend we have a couple of larger events people will rideshare to. Will it be possible to be done with the e-mail notifications and muting functionality by Thursday, @shresthaKiran ?

**Comment by MattiasJay** [comment]
Many issues with these e-mails.

1) We have today tested comments on this ride https://skjutsgruppen.nu/t/39524

Many hours later none of us who have commented have recieved any e-mail @shresthaKiran @anjhero .

2) The link in the group e-mail button links wrong, as we have talked about on Slack.

3) Wrong sender e-mail, as we have talked about earlier concerning all e-mails. They all need to be do-not-reply-email

4) Wrong "from". Right now it says "Hej", it should say "The Ridesharing Movement Skjutsgruppen" (without quotation marks)

Moving this back to issues.

**Comment by shresthaKiran** [comment]
- [x] Add from email name as "The Ridesharing Movement Skjutsgruppen"
- [x] Add from email as "do-not-reply@ridesharingmovement.com"
- [x] Store schedules for sending commented trip email.

**Comment by MattiasJay** [comment]
Oh I meant it should be a version of e-mail that is a do-not-reply-email @shresthaKiran :-D 
The adress of the very e-mail itself can be do-not-reply@ridesharingmovement.com :-D

**Comment by MattiasJay** [comment]
Yesterday one participant posted a ride in the largest group in the app, Sthlm - GBG https://skjutsgruppen.nu/g/149 , but I still haven't recieved any e-mail about that @anjhero @anjesh @shresthaKiran . What do you see in the logs about this?

**Comment by MattiasJay** [comment]
Hi again @shresthaKiran , still no e-mail from the group https://skjutsgruppen.nu/g/149 , and further more I still haven't recieved an e-mail that Daniel and Mira has commented on the previous test ride https://skjutsgruppen.nu/t/39524 .

About the ride, https://skjutsgruppen.nu/t/39524 , could this have something to do with that the system only send e-mails _once_ or something? I'm just guessing, since that's how it appeared to be from a user perspective. I got mail about the first comments but not of the ones that came later. @anjhero @anjesh

**Comment by shresthaKiran** [comment]
@MattiasJay  Is it only with the case of Sthlm - GBG group (https://skjutsgruppen.nu/g/149) or other big groups too?

Also with the case of email notification of comments on trip, bundled comments had been scheduled to be sent after one hour of the first comment but if in the mean time we deploy code to the server or by any means app server gets restarted, then the scheduling gets lost. So as a solution, we have to store those schedules in database, which will be implemented later. 
So for now, is it okay if we send email notification as soon as a user comments on a trip without bundling or scheduling?

**Comment by MattiasJay** [comment]
I'm not in all groups, but yes, it seems to be the same for larger groups @shresthaKiran . Not sure for smaller groups. Would you say there's a difference between the larger and smaller groups?

Sorry to say we don't want to irritate our participants more, which would be the case if we sent them a message for every comment. We already have complaints about too many e-mails. Can you implement the schedules now @shresthaKiran ?

Also, here's an e-mail we got from Sendgrid:

> "Dear SendGrid Customer,
> 
> We are reaching out to let you know that your recent email activity had a high percentage of isp throttling and block rates. This often indicates that ISPs are reluctant to accept the full volume of your mail due to signals they see, such as poor recipient feedback or the reputation of your domain or IP.
> 
> We recognize that email is critical to your business, and we’re here to help you get the most out of your program. As always, you may visit our Support Portal for assistance and to correct any issues with your account.
> 
> For additional guidance, SendGrid offers Expert Services designed to enhance your email program. Services include onboarding help for newer SendGrid users, as well as delivery consulting which can help improve programs of any size or maturity."

Ping @anjhero @anjesh

**Comment by shresthaKiran** [comment]
@MattiasJay Trip comments scheduling has been implemented.
- [ ] Domain authentication in sendgrid

**Comment by MattiasJay** [comment]
Great @shresthaKiran !

**Comment by ruchidhami** [comment]
This issue has been resolved.
