### ISSUE TITLE
The "x shared this with you" is not supposed to show when nothing is shared with me

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#514]
There seems to have been an misunderstanding here. This grey box should only show when something has been _shared_ with me, not as in this case when another participant has just posted something in a group. As you can see it seems like she has shared the whole group with me, which she hasn't. She is not even my friend in the app.

Also, slightly wrong design, see inVision.

![photo_2018-08-26_18-37-08](https://user-images.githubusercontent.com/10048880/44630501-10953000-a95f-11e8-881d-e29a80ab2bed.jpg)

**Comment by shresthaKiran** [comment]
This issue has been resolved.
