### ISSUE TITLE
I can (seemingly, maybe not possibly) remove people from groups I’m not even part of. ...and add.

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#516]
A side effect of that you have implemented that participants can add other participants to groups seems to be that I have the possibility to remove people from groups I’m not even part of. ...and add.  Very weird and strange.

If you go to a group you are not participating in (in Test Flight) and press to see all the participants (without joining the group) you can see how it looks. The pink "X" is there as well as well as the possibility to "add". @shresthaKiran @anjesh @anjhero 

Look closer at this. I should never be able to _**remove**_ participants if I’m not enabler of the group (so the "X" should not be seen).

**Comment by shresthaKiran** [comment]
#519
