### ISSUE TITLE
App crashes on iPhone when trying to open a link to a group

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#517]
@pernillan reports on Trello that the app crashes on iPhone when trying to open a link to a group: https://trello.com/c/MdLhQG07/59-app-crashes-on-iphone-when-trying-to-open-a-link-to-a-group

(photo on Trello)

**Comment by shresthaKiran** [comment]
This issue has been resolved.
