### ISSUE TITLE
Bug with Honor 9 Huawei - don't get pass verifying password

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#518]
One participant reports that he can't get pass the verify password section on his Honor 9 Huawei, Android 8.0.0. He gets to send the SMS but then only comes back to the same place again (send SMS place), so he's stuck.

**Comment by ruchidhami** [comment]
@MattiasJay  It works fine. Please re-open if re-occurs.
