### ISSUE TITLE
Separate window opened when dynamic link is clicked in email in IOS (Safari)

### ISSUE THREAD

**Issue by shresthaKiran** [Skjutsgruppen/skjutsgruppen-reactnative#520]
When a user clicks button (dynamic link) in email from IOS (Safari), then instead of being redirected to the app, a window is shown which contains button that will redirect to app.

![image_from_ios](https://user-images.githubusercontent.com/5945626/45279305-71407300-b4f0-11e8-9bbe-1ec62424d481.png)

**Comment by ruchidhami** [comment]
@MattiasJay  This is the behavior of firebase , we can't handle it from our side .

**Comment by MattiasJay** [comment]
Hi again, yes this is the weird white page I mention in issues #534 and #553 . This is off course very bad since people will mainly see this link from their phone. Same solution is preferred; the skjts.se-link standard.

**Comment by anjesh** [comment]
reiterating what @ruchidhami has mentioned earlier

> This is the behavior of firebase , we can't handle it from our side.
