### ISSUE TITLE
I can't click and open any of my friends in my profile (iOS, iPhone 6)

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#521]

**Comment by shresthaKiran** [comment]
@MattiasJay This has been resolved in latest build. Could you please verify from your end?

**Comment by MattiasJay** [comment]
I now works, but seems to be some lag here and there anyway @shresthaKiran . Like the blue name in a ride (name of participant) is not clickable.

**Comment by shresthaKiran** [comment]
@MattiasJay  Do you mean no. 1 or no. 2?
![not-clickable](https://user-images.githubusercontent.com/5945626/45486523-29814c00-b77b-11e8-94db-359da86e37a1.png)

**Comment by MattiasJay** [comment]
Number one, @shresthaKiran .

**Comment by shresthaKiran** [comment]
This issue has been resolved.
