### ISSUE TITLE
Access to Mobility Management, currently not available

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#525]

**Comment by MattiasJay** [comment]
Any news on this @anjhero and @ruchidhami ?

**Comment by ruchidhami** [comment]
@MattiasJay  It's still working on . Will ping you soon ..

**Comment by ruchidhami** [comment]
@MattiasJay  Mobility management is live now. We can access it from admin panel.

**Comment by anjesh** [comment]
We will not code MM from scratch, rather use the existing mm code and work with our data. There's certain process one needs to follow to create user and give user access to MM.

There will be static information page MM in our admin interface https://skjutsgruppen.nu/admin with the following information.

----

To create MM user 

* Please login to [old skjutgruppen admin page](http://skjutsgruppen.nu:9000/admin/login)
* Go to [users page](http://skjutsgruppen.nu:9000/admin/users) and give MM access

To access MM interface

* Please login to [old skjutsgruppen page](http://skjutsgruppen.nu:9000/users/sign_in)
* Go to [MM page](http://skjutsgruppen.nu:9000/mm) after logging in.

----

With this process, we can use existing codebase to run MM. We will try to see if we can fix existing ruby code to redirect to http://skjutsgruppen.nu:9000/mm after logging from http://skjutsgruppen.nu:9000/users/sign_in

@MattiasJay let us know what do you think about this. We obviously can't do the entire development of MM in new admin interface. 

cc @ruchidhami

**Comment by anjesh** [comment]
@MattiasJay thoughts?

**Comment by MattiasJay** [comment]
I need some hours to test this and get back to you @anjesh @ruchidhami

**Comment by MattiasJay** [comment]
Hi again @ruchidhami and @anjesh , I have now walked through this.

1. Mobility Management (from now on called "MM") is up again! Good job! 

This was the case all the time @anjesh - that we should preserve Mobility Management as it is. It was never supposed to be a new page. This is a page that our partners (mostly Swedish municipalities) can log in to to access statistics about a specific area that we give them access to. I hope @anjhero has communicated this.

2. Since this is a login page we need a better process for our partners to login than the one above. They should not have to go to the old homepage and then enter a new address. Set up a simple address like skjutsgruppen.nu/mm for partners to login.

3. According the specifications and our last meeting @anjesh the delivery is of an "Updated admin panel". To my understanding your suggestion now is to preserve the old admin panel along side the old admin panel because of difficulty, right? 
This will maybe be fine, but we need to have a short meeting about this @anjesh and @anjhero so the board gets the correct details about this.

A thought about this; you seem to have successfully updated the old admin panel so new participants appear there as well. Have you thought about just adding the new features from the new admin panel in the old admin panel instead (and hence deliver the "updated admin panel") ?

4. MM used to have and "participants" section. This seems to be missing.

5. Statistics: we'll discuss this on Slack (see my entry there).

**Comment by anjesh** [comment]
> Since this is a login page we need a better process for our partners to login than the one above. They should not have to go to the old homepage and then enter a new address. Set up a simple address like skjutsgruppen.nu/mm for partners to login.

Yes, we are planning to have a URL like skjutsgruppen.nu/mm, which will take to login page http://skjutsgruppen.nu:9000/users/sign_in or mm.skjutsgruppen.nu/users/sign_in and after signing-in, they will see the actual MM interface (currently at http://skjutsgruppen.nu:9000/mm). We are using 9000 in skjutsgruppen.nu:9000 to run previous code-base. Ideally if you could reset the password for https://www.loopia.se that i asked in slack, then we could setup url like mm.skjutsgruppen.nu and remove the 9000. 

> According the specifications and our last meeting @anjesh the delivery is of an "Updated admin panel". To my understanding your suggestion now is to preserve the old admin panel along side the old admin panel because of difficulty, right?

Yes, but we don't do Ruby, so we created a new admin panel. So admin (yourself and others with admin access) will have to use new url skjustgruppen.nu/admin

> This will maybe be fine, but we need to have a short meeting about this @anjesh and @anjhero so the board gets the correct details about this.

Sure

> A thought about this; you seem to have successfully updated the old admin panel so new participants appear there as well. Have you thought about just adding the new features from the new admin panel in the old admin panel instead (and hence deliver the "updated admin panel") ?

Like i mentioned above, we don't do ruby. 

> MM used to have and "participants" section. This seems to be missing.

The old participants page breaks because of new data structure, so we have hidden that link. Do you need this page? Does that means MM users will be able to see all the participants as well and their details?

> Statistics: we'll discuss this on Slack (see my entry there).

Ok.

**Comment by ruchidhami** [comment]
This is done now. MM can be accessible with new database.

**Comment by MattiasJay** [comment]
I'm looking right now at http://old.skjutsgruppen.nu/mm and there's no data there. It's empty.

I'm assuming it's moved to http://skjutsgruppen.nu:9000/mm @anjesh @ruchidhami ? But that is also a blank page, that can't be opened right now. Have you set the new login page @anjesh ? (we talked about skjutsgruppen.nu/mm )

**Comment by ruchidhami** [comment]
Hello @MattiasJay ,  it can be access through the link http://mm.skjutsgruppen.nu/admin/login for admin access and for mm http://mm.skjutsgruppen.nu. 
Also you can get the instructions of mm by login with the url http://skjutsgruppen.nu/admin.

**Comment by ruchidhami** [comment]
Hello @MattiasJay,
Have you go through the Mobility Management? Is there anything which is missing ? Please provide your thoughts.

**Comment by MattiasJay** [comment]
Hi again @ruchidhami !

Yes we still have issues with 

1. Statistics, see the ongoing discussion we have had about this on Slack

2. Weird interface login at http://mm.skjutsgruppen.nu , how about updating it to look like all other login pages we have (see the other login pages you've made).

3. To make login pages distinct from each other, give the titles/haders (like "Open API", "Mobility Management" and so on)

4.  I have tried to press "List" on the start page of MM for 15 minutes now, and nothing happens :-D . Is that page still valid? I want to see if our participants personal information is exposed here.

**Comment by ruchidhami** [comment]
Hello @MattiasJay ,
 > 1. Statistics, see the ongoing discussion we have had about this on Slack   
  
   Ok. There might be confusion on the statistics .

 > 2. Weird interface login at http://mm.skjutsgruppen.nu , how about updating it to look like all other login pages we have (see the other login pages you've made).
    
Login interface has not implemented from our side. It is an old mm login interface. 
    http://old.skjutsgruppen.nu/users/sign_in

 > 3. To make login pages distinct from each other, give the titles/haders (like "Open API", "Mobility Management" and so on)
   
Can you please provide design mockup? 

>. I have tried to press "List" on the start page of MM for 15 minutes now, and nothing happens :-D . Is that page still valid? I want to see if our participants personal information is exposed here.
   
 Are you talking about this lists? 
![tripslist (1)](https://user-images.githubusercontent.com/13533382/57120329-68a6f080-6d90-11e9-9500-1f130329a063.png)

**Comment by MattiasJay** [comment]
Answer on 3: You can make it very simple; just change the header. Example; where it says "Skjutsgruppen" on this page, change to "Open API for the non-profit ridesharing movement Skjutsgruppen" https://skjutsgruppen.nu/login

Answer on 4: Yes, that's the page. Are there any place on MM where personal information is exposed (like participants full names, e-mail, phone etc?)

**Comment by ruchidhami** [comment]
Hello @MattiasJay, MM is now completed. Please have a look . Please re-open ,if something is missing.

**Comment by MattiasJay** [comment]
Thanks @ruchidhami ! Good job with everything 👍 

These two things from above keeps this issue open:

1. We still have this big question about the correct statistics (se above). I have pinged you in this discussion on Slack, so we can sort it out. Maybe @anjesh and @anjhero has some solutions for this as well?

2. The list from above now loads (though it takes a long time), but many (many) rides loaded there says they have a distance of zero (0) km. 
This is obviously not the case. We can see it directly in the list:

**_Example_**
From: Jönköping -- To: Malmö
Distance: 0 km

It's not 0 km between Jönköping and Malmö :-) 

This makes all the statistics unreliable. This is connected to the discussion we're having on Slack.

And a third thing:

3. I am also limited to only "Sweden" in MM, and it seems hard to see all statistics for me - not limited to a specific area. Can you change my admin role in MM to "Everything everywhere"? Thanks @ruchidhami

**Comment by anjesh** [comment]
> We still have this big question about the correct statistics (se above).

We are not clear on this. We need to understand how you are getting the statistics you shared earlier. 

> The list from above now loads (though it takes a long time), but many (many) rides loaded there says they have a distance of zero (0) km.

The database and existing ruby code probably needs optimisation to make this fast and we don't do ruby. We can do only minor updates but we are not in a position to make major change there. 

As for the 0 km distance, the API returns 0 KM. @ruchidhami will share such instances where 0 km was sent by the API and we have no control over those. We will try to see if anything could be done there. 

> I am also limited to only "Sweden" in MM, and it seems hard to see all statistics for me - not limited to a specific area. Can you change my admin role in MM to "Everything everywhere"? Thanks 

We are using the existing ruby MM code for this. As mentioned above, we don't have expertise to make changes in the ruby code for MM. In existing MM code, there's no such role like "everything everywhere?". It just lists all the counties. We will try to see if anything could be done, but it looks difficult to fix this issue in ruby. We can't commit on this one as of now.

**Comment by ruchidhami** [comment]
Hello @MattiasJay 
 > Example
  From: Jönköping -- To: Malmö
  Distance: 0 km

The above example  **Jönköping - Malmö**  trip was created in the year 2013 and 2014. Since on that time there was no distance on database. so during the data migration process such trips have set the 0 distance value.  

There are various scenario which makes the distance value 0. 

 1. The trips  started let's say from **Anywhere(east, west, north, south) to Malmö**  or **Malmö to Anywhere(east, west, north, south)** has set the distance 0. 
2. Old trips before the data migration has set the distance value 0.
3. Since google API was unable to find the route between staring and end point , in such case API returns 0 KM, and we have no control over this. For now, we have handle this from app side.
