### ISSUE TITLE
"Share to Facebook and Twitter" should be seen as share options EVEN if participant has not connected to Facebook and Twitter yet.

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#526]

**Comment by shresthaKiran** [comment]
- [x] Display "Your Facebook Timeline" and "Tweet" options in share even though user hasn't linked fb or twitter
- [x] Preselect "Your Facebook Timeline" and "Tweet" options in share if user has linked fb and twiiter.
- [x] Link to facebook if share with facebook is selected and user hasn't linked fb.
- [x] Link to twitter if share with twitter is selected and user hasn't linked twitter.

**Comment by MattiasJay** [comment]
This is weird 

You can also see issue #538 about this @shresthaKiran @anjesh @anjhero @umuieme 

...but it seems like I can login from onboarding with Facebook, but nothing happens when I'm trying to share to my Facebook timeline. Are you guys able to share to your Facebook timelines?

**Comment by ruchidhami** [comment]
@MattiasJay I have look over this issue and it works fine. In which section you have been facing problem?

**Comment by ruchidhami** [comment]
This issue has been resolved.

**Comment by MattiasJay** [comment]
I have now followed this process:

1) Made sure my Skjutsgruppena account is not connected to my Facebook account (I've deleted all prior connections)
2) Added a ride in the group Chobhar
3) On the last step clicked to share to Facebook timeline and Twitter
4) ...nothing happens, it just loads.
5) ...had to force quit the app

I've added a short video about the process for you on Slack @ruchidhami . Ping @anjhero .

**Comment by ruchidhami** [comment]
@MattiasJay  Can you please verify?

**Comment by ruchidhami** [comment]
@MattiasJay  Have you got chance to look this issue?

**Comment by anjesh** [comment]
Closing this. Please verify and open if any issue.
