### ISSUE TITLE
Participant number 37013 have been able to create an account without a name, and/or deleted her name afterwards within the app. In either case, this should not be possible.

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#528]

**Comment by MattiasJay** [comment]
This has now been done by new participant, number 38001, as well, so this seems to not be done. Moving it back to the issues column @shresthaKiran @anjhero

**Comment by ruchidhami** [comment]
This issue has been resolved.

**Comment by MattiasJay** [comment]
This has happened again today with participant 40394 created today. @ruchidhami

**Comment by ruchidhami** [comment]
This issue has been re-solved. Please re-open , if occurs.
