### ISSUE TITLE
code rendering advertised paid promo "unclickable" no revenue 444 clicks

### ISSUE THREAD

**Issue by Lorindellia** [Skjutsgruppen/skjutsgruppen-reactnative#529]
<div class="unclickable fbInternPreview _4nw2 _605a">

`<iframe` src="https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2FGrandsBirthdays%2Fposts%2F855694898152431&width=500" width="500" height="631" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true" allow="encrypted-media"></iframe>``

**Comment by anjhero** [comment]
Not sure what you mean here. Could you explain a bit more?

**Comment by ruchidhami** [comment]
Please re-open if needed.

**Comment by Lorindellia** [comment]
Okay so I created a link with a pay per click revenue: I recieved 444 clicks, Yet no revenue.

I suspect there is a script placed by Face B that is blocking my revenue.  Can anyone help me identify the script?
