### ISSUE TITLE
Reports of people not being able to restore their password.

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#531]
Seems like people are not getting the resore password e-mail. @anjhero @anjesh @umuieme

**Comment by ruchidhami** [comment]
@MattiasJay  Restore password works fine.. Which user not able to restore password? Can you please provide id of that user?

**Comment by ruchidhami** [comment]
@MattiasJay  Any update on this ?

**Comment by MattiasJay** [comment]
I think this might be a problem with the general e-mail problems we seem to be having @ruchidhami
