### ISSUE TITLE
Wrong in the Experience functionality: not all who are in the Experience have gotten the Experience on the profile page.

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#532]
Look at the Experiences made in the app. Currently just the one who took the photo has the Experience on his or her personal page. This is wrong. All tagged in the Experience should have the Experience.

**Comment by shresthaKiran** [comment]
@MattiasJay  This issue has been fixed. Please re-open if issue still exists.

**Comment by MattiasJay** [comment]
Good @shresthaKiran . Can you also move the card in the Kanban board when fixing so we have a continued overview? Big thanks! @anjhero
