### ISSUE TITLE
No tweet made when I was commenting on a ride and pressed that tweet should be made (the Twitter check box above the comment, when commenting)

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#534]

**Comment by shresthaKiran** [comment]
@MattiasJay I just tested this on ios and tweet about comment made on offered ride was tweeted.
![offered_twitter_comment](https://user-images.githubusercontent.com/5945626/47833159-7d92cf00-ddc1-11e8-8ebf-96ec1c10668f.png)

**Comment by MattiasJay** [comment]
Hmm this is not happening for me, and Facebook is not happening for me either as we can see in another issue. Have you tried this with a completely new participant account as well @shresthaKiran ?

**Comment by MattiasJay** [comment]
The Twitter stuff seems to work partly now @shresthaKiran . But as you can see on both your and my tweet here the link is wrong: https://twitter.com/skjutsgruppen/status/1061708725747105793

It should be the correct short link (skjts.se). On my phone it doesn't even open, on laptop it redirects and then open.

**Comment by ruchidhami** [comment]
@MattiasJay  Short link can be like https://skjuts.page.link/WXYZ  . We can't make short link as https://skjts.se/g/604 ,as it was auto generated by firebase console.

**Comment by ruchidhami** [comment]
referenced on  #553

**Comment by MattiasJay** [comment]
Ok we need to find a way to work around this @ruchidhami @shresthaKiran and @anjhero . The current auto generated links has never worked for me when trying to open from my Twitter mobile application. I always get to a white page first, and then an error message. Have you tried to open this from Twitter mobile application? The skjts.se-short link was created for this purpose and is the standard we have used the latest years. What are your suggestions on this?

**Comment by ruchidhami** [comment]
This issue has been solved. As per discussion ,now the short link appears as **https://skjts.page.linl/8Ng4** . @MattiasJay  Can you please confirm this ?

**Comment by anjesh** [comment]
Reopen if any issue.
