### ISSUE TITLE
Search problem: recurring ride / return rides do not appear in search result. Also the cards of these rides have more issues.

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#535]
This participant has a return ride from Skövde to Linköping on November 16th:

![photo_2018-10-31_13-25-17](https://user-images.githubusercontent.com/10048880/47787883-8d060f80-dd10-11e8-97ed-ee79cd535a27.jpg)

Please note that this is the **_recurring_** **_return ride_**, since this may be important.

When searching for this exact date and distance, Search gives no ridesharing results:

![photo_2018-10-31_13-25-05](https://user-images.githubusercontent.com/10048880/47787977-c2aaf880-dd10-11e8-960b-e56d312cfb9e.jpg)

Also, I can't share the link to the ride because the sharing icon does not appear in the upper right corner here when scrolling:

![photo_2018-10-31_13-25-10](https://user-images.githubusercontent.com/10048880/47788036-e3734e00-dd10-11e8-9f90-5805e89dc177.jpg)

And neither in the "three dots" hamburger menu here: 

![photo_2018-10-31_13-25-13](https://user-images.githubusercontent.com/10048880/47788101-09005780-dd11-11e8-971a-0b4193c2c94e.jpg)

@anjhero @anjesh @shresthaKiran

**Comment by shresthaKiran** [comment]
@MattiasJay Regarding the search result, you have set your destination place to **Linköping**, but the actual ride has destination place to **Lidköping**, so you didn't get the desired result. 

As per the design (https://projects.invisionapp.com/d/#/console/12489615/262842860/preview), there is no share button in the three dot menu. The share button is present on the top right side of the trip detail page.

**Comment by MattiasJay** [comment]
Great! Then we can close this issue, thanks @shresthaKiran !
