### ISSUE TITLE
Urgent: the timing of the Experience functionality

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#536]
I'm bumping this one up as urgent.

As you saw, this is what our board member Lovisa reported on Slack:

> "Hi! Input about the app and the experience-function. When I rideshared, the questions about whether or not we wanted to make an experience came after the ride was supposed to be done. It was only because we where delayed that we were still in the car when the question came so we could do it. So that is a problem that needs to be solved. And it probably explains why not so many people have not done so many experiences. "

We have been very curious as to why our participants don't use this lovely functionality, and now we may have the answer @umuieme @anjesh . I think this is now set to appear to a specific time in the ride, but as Lovisa points out this comes to late. So instead of an algoritm, how about we set it to one hour after start?

**Comment by ruchidhami** [comment]
@MattiasJay  This issue has been resolved. Please re-open if occurs.
