### ISSUE TITLE
Example of getting stuck: Can't go back from step 8 on Android after *not* sending text message.

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#537]
![photo_2018-11-11_20-04-19](https://user-images.githubusercontent.com/10048880/48317082-08a76c80-e5ed-11e8-8bc9-b0a33df89ba5.jpg)

**Comment by MattiasJay** [comment]
...it also says "well done" for some reason for each step 😄 (previously it was only for the last step)

**Comment by ruchidhami** [comment]
This issue has been resolved.
