### ISSUE TITLE
Urgent: Stuck on e-mail when onboarding

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#539]
I get stuck on this screen @anjhero  @anjesh  @umuieme  . This is the wrong e-mail and I figured out what e-mail it was instead, but the app don’t let me get back from here. I can’t press ”back” and fill in another adress. We also have an one star review about this exact same issue in the Android Play Store.

![image from ios](https://user-images.githubusercontent.com/10048880/48318019-7f973200-e5fa-11e8-8af5-353540d136d9.jpg)

**Comment by ruchidhami** [comment]
@MattiasJay  This issue has been resolved.
