### ISSUE TITLE
On some rides stop along the way are not seen until map is opened big (full screen). Not on small map in small card in start feed or even when opening card.

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#540]
Example: https://skjutsgruppen.nu/t/41317

![photo_2018-11-16_17-38-34](https://user-images.githubusercontent.com/10048880/48634754-a375c180-e9c6-11e8-9895-3f70b3406ecf.jpg)

**Comment by ruchidhami** [comment]
This issue has been resolved.
