### ISSUE TITLE
Open API Development for Trips

### ISSUE THREAD

**Issue by anjesh** [Skjutsgruppen/skjutsgruppen-reactnative#543]
- [x] design the API (request/response) for list of trips
- [x] design the API (request/response) list of comments for a given trip
- [x] develop the API for list of trips
- [x] develop the API for list of comments for a given trip
- [x] API should be authenticated, only the registered users should be able to make call to API

We don't need all the APIs listed in [this document](https://github.com/Skjutsgruppen/OpenAPI).

**Comment by ruchidhami** [comment]
@MattiasJay  Can you please provide the list of information to be open?

**Comment by ruchidhami** [comment]
reference on #547
