### ISSUE TITLE
Deleted participant is still not fully deleted

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#546]
This needs to be fixed @anjhero @ruchidhami . And this is very important as we have stated before.
Today when I created a new account with a phone number I used before, but the account and participant is supposed to be deleted, it still sayed that my phone number was already in use and I had to log in. The username that was prefilled when I logged in was "Deleted participant", which we know is an automatical name the system gives to deleted participants. So, the system in one way thinks the participant is deleted ...but it's not.

**Comment by MattiasJay** [comment]
...I also can't change my name on this account. Look at account with participant number 36162

**Comment by ruchidhami** [comment]
@MattiasJay  we had tested it properly  and  it works in both android and IOS.  Can you please provide the id of that deleted participant. And also changing my name looks fine in both devices .

**Comment by MattiasJay** [comment]
@ruchidhami , participant number 36162

**Comment by ruchidhami** [comment]
@MattiasJay  Did you trying to delete the participant number 36162? or you are not able to change the name of that participant? Can you please provide the id of that deleted participant so that I can confirm it in database what the actual problem is.

**Comment by ruchidhami** [comment]
@MattiasJay  Any update on this ?

**Comment by ruchidhami** [comment]
This issue has been resolved. Please re-open if occurs.
