### ISSUE TITLE
Search don’t find the Dreamhack group I’m part of

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#550]
Nowhere where I use search, like sharing a ride I have not created, or in my own messages and groups I find the group "Dreamhack" that I'm a part of. See videos and pictures of this on Slack, November 28th.

**Comment by MattiasJay** [comment]
Just for your information; I still don't find my groups when adding rides and searching for my groups to add rides (example: step 5 when offering a ride from the "+" in the menu) @ruchidhami

**Comment by ruchidhami** [comment]
Just for your information; I still don't find my groups when adding rides and searching for my groups to add rides (example: step 5 when offering a ride from the "+" in the menu)
> @MattiasJay  To make the search smooth and prevent it from lagging , we had implemented here the front-end search. Since there is pagination in group listing, so all of **my groups** has not been loaded, if we click **+ more** and then search for my groups it will works . 
 Can you please confirm?

**Comment by ruchidhami** [comment]
@MattiasJay  This issue has been resolved. I am closing this issue. Please re-open it not works.
