### ISSUE TITLE
Wrong link when tweeting.

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#553]
The links on Twitter are in the style of pwm3h.app.goo... instead of the skjts.se short link.

Example: https://twitter.com/kaleruchi5/status/1077434337358950403

**Comment by ruchidhami** [comment]
Hi @MattiasJay This issue is already opened.  I had mentioned you in a comment of a issue no. #534 .

**Comment by ruchidhami** [comment]
referenced on #534
