### ISSUE TITLE
We have a participant who can't get through the SMS verification process on his iPhone 6. I have tried to figure it out with him, but nothing seems to help. What do we need to figure this out?

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#556]

**Comment by ruchidhami** [comment]
@MattiasJay  Have you try after re-install the app again? Or either you can provide me the email of that participant , I can check from here . I am not sure what the actual problem is . But may be this is the app's cache issue.

**Comment by ruchidhami** [comment]
@MattiasJay  Have any update on this ?

**Comment by ruchidhami** [comment]
@MattiasJay  Have you got chance to look over this ?

**Comment by anjesh** [comment]
Reopen if the issue persists.
