### ISSUE TITLE
Wrong design on step 4 of 4 offering/asking for a ride

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#557]
Here's what the design should look like: https://projects.invisionapp.com/d/main#/console/12489615/275340458/preview

**Comment by ruchidhami** [comment]
@MattiasJay  Can you please confirm it from the below screenshot? 
![screenshot_skjutsgruppen_20190104-141036](https://user-images.githubusercontent.com/13533382/50679221-b3a33800-102a-11e9-8ae2-e44ed859f777.png)

**Comment by ruchidhami** [comment]
@MattiasJay  This issue has been resolved.
