### ISSUE TITLE
Look at the map on the small map on this ride detail. It's wrong. Then open...

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#558]
Look at the map on the small map on this ride detail: https://skjutsgruppen.nu/t/42995
It's wrong. Then open the larger map and see the correct map. 

I've provided a short film about this on Slack @ruchidhami .

**Comment by ruchidhami** [comment]
@MattiasJay  Are you talking about stops in small and larger maps? If yes , small maps are the images which was generated at the time of trip created. Also referenced on closed issue #540 . There was an issue during the map created . But now it has been fixed. But we can't change those images  which was created before. But it would works for upcoming image map. Can you please confirm this ?

**Comment by ruchidhami** [comment]
@MattiasJay  This issue has been solved. Please open if re-occurs.
