### ISSUE TITLE
Problem register 

### ISSUE THREAD

**Issue by kfranco89** [Skjutsgruppen/skjutsgruppen-reactnative#561]
Hi i have problem when i wanna register a user 
![screenshot from 2019-01-19 11-17-24](https://user-images.githubusercontent.com/46143528/51429345-dcefc680-1bdb-11e9-9654-05da69046c02.png)

this is my conf .env 

API_URL=localhost:4000
WS_API_URL=localhost:4000
GOOGLE_MAP_API_KEY=google_map_api_key
SMS_NUMBER=966230
TWITTER_CONSUMER_KEY=twitter_consumer_key
TWITTER_CONSUMER_SECRET=twitter_consumer_secret
FB_ID=369176403910
FB_LOGIN_SCHEME=fb3691764039
FABRIC_API_KEY=c8e2c7009e1c365d035
APP_URL=localhost:8081

**Comment by ruchidhami** [comment]
Hello @kfranco89 , you have to set the real data in .env file.  If you need any kind of help please feel free to ask .
