### ISSUE TITLE
The button "Open in app" on web version of cards doesn't work (iOS)

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#563]

**Comment by ruchidhami** [comment]
@MattiasJay  Now, it works .

**Comment by MattiasJay** [comment]
I'm trying this on iPhone 6 right now, and it does not open the app @ruchidhami . Is it because the newest version of the app is not in App Store yet? @umuieme @anjesh

**Comment by ruchidhami** [comment]
Yes @MattiasJay  newest version was not in app store before, now it is app store , Can you please confirm it ?

**Comment by MattiasJay** [comment]
Now it works! Great job @ruchidhami !
