### ISSUE TITLE
Missing options in rides that you have created yourself

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#564]
A couple of our participants have reported that they can't delete their own rides. I thought this must be that they just did not find the menu, but no - they are correct. Look at a ride that you have created yourself and press the three dots in the lower left corner; many options are missing that used to be there @ruchidhami @anjhero

**Comment by ruchidhami** [comment]
@MattiasJay  Now all options are appears in rides . This issue has been resolved.
