### ISSUE TITLE
When you've taken a photo as an profile photo in the onboarding process, you can't proceed to the next step

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#567]
I tried this with a participant this weekend. We could not get to the next step. iOS.

![photo_2019-03-03_18-13-32](https://user-images.githubusercontent.com/10048880/53698657-1cffb700-3de0-11e9-8425-e6700e358f1b.jpg)

**Comment by ruchidhami** [comment]
Hi! @MattiasJay , Can you please confirm this issue ? This has been solved from our side.
