### ISSUE TITLE
The Self-Sustaining Garden - round-up before release March 13

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#568]
- [x] Reflect the % changes in the bars. @umuieme said on a meeting that the % changes from year one to year two, and then stays the same. This needs to be reflected in the bars. 

- [x] Where it applies; it should say "A self-sustaining garden" instead of "An"

- [x] Correct design of card in the start feed when someone has supported. The correct design is found here: https://invis.io/ESQZPEDWU9K#/262118123_Feed

- The bar we're currently filling up is the one that should be seen (IF the first bar is 100% then the second bar should show here, and so on. Not all three bars)

- [x] The button in the card in the start feed when someone has supported shall go to the start of the self-sustaing garden process (that's the same as when you click the "trees and sun" in the app menu.

- [x] Slow down the animation in the bars. Make it 60% slower.

- [x] Add the correct currency (SEK), the correct titles and correct amounts. The correct currency, titles  and amounts are:

- Server, domains - 19 299 SEK/year
- Programming - 100 000 SEK/year
- Project Manager - 430 000 SEK/year

(you also find these on this screen: https://invis.io/MTQX7KLGC6K#/295156671_Support_Goes_To )

![photo_2019-03-13_19-44-16](https://user-images.githubusercontent.com/10048880/54306277-492deb80-45c9-11e9-99a4-61820196506b.jpg)

- [x] Spacing and texts and line breaks are wrong in this design @umuieme : 

- IF applied, the amount supported and the number of months should be on two separate lines.
- The second part should be in a correct sentence, like provided. Currently words are missing.
- The "Total" is to be separated from the rest by two lines, with correct spacing and the last sentence in italic.

![wrong_with_garden](https://user-images.githubusercontent.com/10048880/54307650-7039ec80-45cc-11e9-806b-d45eef2fe28e.jpg)

- [x] In "Logo and brand" section; Change from "The ability to add your logo to your rides" to "The permission to show your logo and brand"

- [x] I see that you have added some Apple information after all @umuieme , change this in the order of the design on inVision, so the Apple info comes last as in the design.

- [x] Also, what does this mean: "Any unused portion of a free trial will be forfeited if you purchase a subscription"? ...since we don't have free trials? You can answer this on Slack or as a comment below.

- [x] Add the lines between the info and "Further conditions..." as in the design.

- [x] Make the white box with final "support" button larger, like in the design. We need a bit more surrounding white spacing so it stands out.

- [x] The same text is repeated here three times: 

![photo_2019-03-13_20-33-17](https://user-images.githubusercontent.com/10048880/54308885-459d6300-45cf-11e9-93ab-7a2c4a4eecc2.jpg)

...see the correct texts on inVision.

**Comment by MattiasJay** [comment]
@umuieme I have tried to support and then stopped supporting. This does not seem to be reflected on my "Your support"-page.

I also want to double check on these two things:
1) What will happen when the time run out? (after six months I guess?)
2) How is this reflected in the bars, after I quit supporting?

**Comment by umuieme** [comment]
@MattiasJay There are few issues in this picture.
The part with the line break in 9 Kr every month for six months, since we don't divide the amount to per month, that part may sound double. also the description below that is not correct in our scenario I think.

https://user-images.githubusercontent.com/10048880/54307650-7039ec80-45cc-11e9-806b-d45eef2fe28e.jpg

**Comment by MattiasJay** [comment]
Hi @umuieme , you're correct that we should not divide by months anymore. Let's break it down like this to make it cleaner looking and more straight forward:


10 kr
one month

This support is auto-renewed every month.

----

29 kr
one month 

This support is auto-renewed every month.

----

589 kr
one year

This support is auto-renewed every year.

----

1749 kr
one year

This support is auto-renewed every year.

-----

2995 kr
six months

This support is auto-renewed every sixth month.

-----

What do you think about this @umuieme ?

**Comment by MattiasJay** [comment]
Or hmm... maybe that is confusing. What do you think @anjesh @umuieme @ruchidhami @anjesh , should we just skip the sentences "You have supported six months so far."? I mean, we still show the below how much they have supported so far. What is best?

**Comment by anjesh** [comment]
I agree. Lets remove the confusing sentence - it's self-understood and there's info at the bottom as you have mentioned.

**Comment by MattiasJay** [comment]
Good, then proceed with this. For clairty I have updated the texts above and removed the confusing sentences.

**Comment by MattiasJay** [comment]
Feedback from testing on Android:

1. It still says "Programmer" instead of "Programming" (see photo on Slack #garden )

2. Concerning how we phrase it, look at the text above (from March 14) and the screen shot below:

![photo_2019-03-20_21-59-53](https://user-images.githubusercontent.com/10048880/54718751-88c17e00-4b5b-11e9-8d6c-879d9f8ff7cd.jpg)

Above we made a specific version for each of the things one participants can support, to make it cleaner and clearer. 

Example comparing with the screenshot:

**The screen shot says**

29 kr every 1 month(s)

This support is auto renewed every 1 month(s).

**It should say (according to above)**

29 kr
one month

This support is auto-renewed every month.

@anjesh @umuieme

**Comment by MattiasJay** [comment]
Yesterday my support appeared in the feed again.

The feed entrys of participants supporting are only supposed to happen _when they start supporting_, not every time a new month and/or year starts @ruchidhami @anjesh @umuieme . As you can see the text is very confusing if it is like it is now; "Mattias just supported..." (since I didn't, this was just automatic)

The only case they would happen again is IF the participant have stopped supporting --> not been a supporter --> supports again.

![GitHawk Upload by MattiasJay](https://i.imgur.com/C7esh5p.jpg)

**Comment by ruchidhami** [comment]
Hello @MattiasJay, 

It's seems confusion on this part.
Firstly you've supported for the plan **55 Kr per six month** on `2018-10-14` and it auto-renewed automatically after six months  i.e on `2019-04-18` and on that time feed card has not created . And now you've supported for **29 Kr per month** on `2019-05-18` which is a new plan. This case is not a auto-renewal case and that's why new card has created on feed.

Please, give your thoughts and correct me if I am wrong.

**Comment by MattiasJay** [comment]
This is interesting. I'm looking right now on my subscriptions in the iTunes Store and can conclude that I only have the 29 SEK/month subscription. I don't have the 55 SEK anymore, as should be (since we don't have that option in the garden). 

However, when I started my 29 SEK subscription it actually got a card in the feed, I checked for this and that is what happened. It seems to be in accordance with the payment as well. This is what iTunes says; 

> I started my 29 SEK subscription on _April 28 2019_

(that created a card in the feed)

> It will auto-renew on May 18 2019 

The card on 2019-05-18 seems to correlate with the aut-renewal @ruchidhami ?

**Comment by ruchidhami** [comment]
Hello @MattiasJay ,
I was confused on the 55kr plan, since there is no such type of plan for now. That plan was created during the testing phase and was inserted on database. I got your point, I will fix it soon and will ping you. :)

**Comment by MattiasJay** [comment]
Thanks @ruchidhami ! This was a tricky one, so it would have been hard to spot without looking through iTunes and see how it turns out. Thanks for working on it!

**Comment by MattiasJay** [comment]
Also @ruchidhami , this is wrong. I have now supported two times (two months) with 29 SEK each month. But as you can see in this screenshot from today it doesn’t show in the total: ![GitHawk Upload by MattiasJay](https://i.imgur.com/dIAdtsk.jpg)

@anjesh @umuieme 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MattiasJay** [comment]
This happened today again for another participant @ruchidhami :


> The feed entrys of participants supporting are only supposed to happen _when they start supporting_, not every time a new month and/or year starts @ruchidhami @anjesh @umuieme .

**Comment by ruchidhami** [comment]
Both issue has been solved @MattiasJay 
> The feed entrys of participants supporting are only supposed to happen when they start supporting, not every time a new month and/or year starts

> this is wrong. I have now supported two times (two months) with 29 SEK each month.

**Comment by MattiasJay** [comment]
This view is still confusing @ruchidhami , we have to get this right:

![GitHawk Upload by MattiasJay](https://i.imgur.com/REFgt4o.jpg)

This is what we need to do:

1) Look at the design here: https://projects.invisionapp.com/d/main?origin=v7#/console/12489615/295069413/preview

Look at how the different sums have their own sections. Let's bring that back, that would make it less confusing.

- [ ] Every support (every sum) should have it's own section.

2) If you look above we cleared how it was supposed to look on March 14th @umuieme @ruchidhami @anjesh , and then again on March 20th (the entry below March 14th) : https://github.com/Skjutsgruppen/skjutsgruppen-reactnative/issues/568#issuecomment-472790691

It seems to be clear how the sentences are supposed to be, now we have have to implement it. Ask me if anything is unclear about the March 14th decision.

- [ ] Implemented the March 14th decision.

**Comment by umuieme** [comment]
> 1. Look at the design here: https://projects.invisionapp.com/d/main?origin=v7#/console/12489615/295069413/preview
> Look at how the different sums have their own sections. Let's bring that back, that would make it less confusing.
> 
>   Every support (every sum) should have it's own section.

@MattiasJay  Regarding the design in the invision, how should be show the renewed packages. For example if 29 Kr/month is renewed and there are two transaction for 29Kr/month, how to show those two transaction?

**Comment by MattiasJay** [comment]
Hi @umuieme ! Do you mean _IF_ a package is renewed?

**Comment by umuieme** [comment]
@MattiasJay Yes thats what i mean.

**Comment by ruchidhami** [comment]
Hello @MattiasJay , any update on this ?

**Comment by MattiasJay** [comment]
There can't be two 29 SEK supports _live_ at the same time, since neither Apple or Google allows that.
 IF you have previously supported with 29 SEK and THEN stopped, and then started again later, there will still only be one (1) active support. 

Look at the decision with @anjesh from above, we decided to skip the sentence "You have supported six months so far."? and make it more cleaner. 

1. An **ongoing support** would have the text "This support is auto-renewed every month." (or _year_ or _six_ _months_ if that is the case)

2. IF a support has stopped the the text "This support is auto-renewed every month." can be replaced with **_This support has stopped_**.

As always, I would love to get your input on this just like @anjesh did in the above discussion, since this is tricky. What do you think?
