### ISSUE TITLE
Support garden users can add photo to their ride

### ISSUE THREAD

**Issue by anjesh** [Skjutsgruppen/skjutsgruppen-reactnative#571]
- [x] photo add feature to the ride in "Offer a ride"
- [x] photo add feature to the ride in "Ask for a ride"

This is only possible if you are a supporter of The Self-Sustaining Garden. So, this is an add-on feature for participants who pay real money to the benefit of the movement.

@ruchidhami

**Comment by ruchidhami** [comment]
@MattiasJay  Now , supporter user can upload images to their ride.
