### ISSUE TITLE
Last things - embed a ride

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#573]
Here's a separat issue for embedding a ride, so we don't confuse it with embedding a group @ruchidhami .

Almost done here as well!

- [x] Add height % in the code here as well: <iframe src="http://skjts.se/t/4590" frameborder="0" width="100%"></iframe>

- [x] Subject line should be "(participant_Name) got the code to embed your ride", in this case it would look like this: Ruchi got the code to embed your ride

**Comment by ruchidhami** [comment]
@MattiasJay  It has been implemented.
