### ISSUE TITLE
Updated screen in "Support to add photo" box during offer a ride/ask for ride

### ISSUE THREAD

**Issue by anjesh** [Skjutsgruppen/skjutsgruppen-reactnative#574]
- [x] screen is added in offer a ride/ask for ride in "add photo" link

Here's the updated "Support to add photo"-box @channel, with links in inVision that shows what happens when clicked. Just like all other boxes the background should be greyed, just like before. You can trie it out by going to "Offer a ride" on inVision and press the "add photo" circle. The design in on the Google Drive.
https://skjutsgruppen.slack.com/archives/C70PVU8S3/p1552400148008700

![image](https://user-images.githubusercontent.com/120488/54254078-7bfcc300-457a-11e9-8f84-9d29071e4c11.png)

**Comment by ruchidhami** [comment]
This has been implemented as per screen.

**Comment by MattiasJay** [comment]
As @anjesh wrote above, the box background should have the standard transparent grey. Right now it hasn't. 

![wrong_design_garden_popup](https://user-images.githubusercontent.com/10048880/58105030-19611c80-7be6-11e9-9758-52301d431eb6.jpg)

- [x] Fix so the text "Support the garden to add a photo" is centered as has the correct spacing

- [x] Fix standard transparent grey background

@ruchidhami @RaiSaugat

**Comment by ruchidhami** [comment]
@MattiasJay  Please verify this issue, it has been pushed on test flight.

**Comment by MattiasJay** [comment]
Hi @ruchidhami , I'm locked out from verifying this issue, since my account already is an paying account (supporter). An easy way: Can you make a screenshot on an iPhone and an Android and post here?

**Comment by umuieme** [comment]
Here is the screenshot for ios

![IMG_113B3E45FFC3-1](https://user-images.githubusercontent.com/13749337/58850919-5500e980-86b0-11e9-8165-3a646d529b89.jpeg)

And here is the screenshot for android

![IMG_113B3E45FFC3-1](https://user-images.githubusercontent.com/13749337/58851397-54695280-86b2-11e9-8ec0-4cfe4fc720fc.jpeg)

**Comment by MattiasJay** [comment]
This seems to be a mix of Swedish and English @umuieme and @ruchidhami ?

Tell me more about this.

**Comment by umuieme** [comment]
The translation was not available when i updated the screen. but it has been implemented in testflight. This is the updated screenshot


![IMG_23952D3AD35D-1](https://user-images.githubusercontent.com/13749337/59243569-5db56a80-8c30-11e9-876c-5d2dd806a499.jpeg)

**Comment by MattiasJay** [comment]
Looks good now @umuieme @ruchidhami !
