### ISSUE TITLE
Update text for "How garden works"

### ISSUE THREAD

**Issue by anjesh** [Skjutsgruppen/skjutsgruppen-reactnative#575]
- [x] text is updated

Now the rest of the "This is how the garden works" (or support_goes_to) page is filled in @Umesh Basnet, and the updated PSD is on the Drive:  https://invis.io/MTQX7KLGC6K#/295156671_Support_Goes_To

**Comment by ruchidhami** [comment]
@MattiasJay  This screen has been implemented.

ping @anjesh dai .
