### ISSUE TITLE
Remove "Co create this app" screen

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#576]
We are now getting to a close of this part of the project,
and will for now remove this screen that appears every time a participant opens the app:

![Image from iOS (1)](https://user-images.githubusercontent.com/10048880/54747656-cbbd3900-4bcf-11e9-9365-f0a011b3bc17.png)

@anjhero @anjesh

**Comment by ruchidhami** [comment]
This is done.
