### ISSUE TITLE
The blue "new notifications" dot next to the speech bubbles (symbol for "Messages & groups") are visible even though there are no new notifications.

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#577]
ios

**Comment by anjesh** [comment]
Fixed. Will be reflected on next update.

**Comment by MattiasJay** [comment]
Thanks @anjesh !

**Comment by ruchidhami** [comment]
@MattiasJay  This issue has been re-solved and reflected on app. It takes 5-6 sec to reflect if there is no any new notifications.

**Comment by MattiasJay** [comment]
Thanks @ruchidhami ! Good job on this! @anjesh
