### ISSUE TITLE
After deleting my ride I just come to a totally white screen. There's nothing there and noting happens. Have to close and restart the app. iOS, iPhone 6.

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#578]

**Comment by MattiasJay** [comment]
This is still the case today. If you trie to delete a ride you have made @ruchidhami @umuieme , do you see this as well?

**Comment by ruchidhami** [comment]
Yes we're aware about this issue.. This has been solved and pushed upto test flight. Please have a look on test flight and confirm it.

**Comment by MattiasJay** [comment]
Thank you @ruchidhami !

**Comment by ruchidhami** [comment]
Hello @MattiasJay  Could you please verify this issue? It has been pushed in test filght.

**Comment by ruchidhami** [comment]
This issue has been resolved many days before. @MattiasJay
