### ISSUE TITLE
Big group error; a new group is not created if... (many reports about this)

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#582]
Hi @ruchidhami , we have a big recurring error the last days that is now confirmed. A new group is not created IF participant tries to share it with his or her phone book contacts on step 5. 

It seems like everthing is going well all the way, and even the "Publish" on top of the screen is seen like thi (see the picture below), but then it's not published anyway.

![photo_2019-05-06_12-32-23](https://user-images.githubusercontent.com/10048880/57220283-0a317a80-6ffb-11e9-9676-e6aa84cd42e8.jpg)

**Comment by ruchidhami** [comment]
Ok! @MattiasJay, We will resolve this ASAP.

**Comment by MattiasJay** [comment]
Thank you @ruchidhami !

**Comment by anjesh** [comment]
Done. Will be reflected on next update.

**Comment by MattiasJay** [comment]
Thanks @ruchidhami and @anjesh !
