### ISSUE TITLE
Crash report: When you press a date in the calender in groups, that does not have a color (pink or blue) the app crashes (iOS)

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#590]

**Comment by umuieme** [comment]
@MattiasJay Can you tell me which group are having these issues or the video recording. Its working without crash when i tested.

**Comment by MattiasJay** [comment]
Hmm I'm not able to recreate the issue. I know this happened on an older iPhone, but since I can't recreate the issue right now I suggest we close this and you focus on the Swedish translation instead @umuieme . @anjesh
