### ISSUE TITLE
UI Fixes

### ISSUE THREAD

**Issue by normacdylan** [Skjutsgruppen/skjutsgruppen-reactnative#627]
- [x] center bottom tab icons

- [x] center texts in buttons in Add-tab

- [x] center button on Ride

- [x] Split comment suggestion in two lines

- [x] center share-button in share with modal

- [x] replace feedback on touchable opacity

-

**Comment by MattiasJay** [comment]
Hej igen @normacdylan ! Bra jobbat.
Jag har avcheckat "center button on Ride" för de knapparna ligger fortfarande till vänster på olika rides istället för centrerade.

Angående menyn, hur gick det med att ta menyn från "Discover groups" rakt av?
